var EEG_EXERCISES = [

  // ── STAGE 1: FOUNDATIONS ─────────────────────────────────────────────────
  {
    id:1, stage:1, stageTitle:"Foundations",
    title:"The 10–20 Electrode System",
    concept:"Electrode placement is the grammar of EEG.",
    body:"The 10–20 system places electrodes at defined percentages of skull length. Labels encode location: F frontal, C central, P parietal, O occipital, T temporal, Fp frontopolar. Even numbers = right hemisphere, odd = left, z = midline.",
    keyPoints:["Odd = left, even = right, z = midline","Letters encode lobe: F, C, P, O, T, Fp","Without knowing the electrode, a finding means nothing"],
    imageNote:"Standard 10–20 electrode positions.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Electrode O2 is on which side?",
      options:["Left hemisphere","Right hemisphere"],
      answer:1,
      verdict:"Right hemisphere",
      subtitle:"Even numbers are always right-sided.",
      why:"O stands for occipital. The number 2 means right hemisphere. In the 10–20 system, even = right, odd = left, z = midline — every time, no exceptions.",
      mistake:"Confusing the number convention. Memorise it once: even = right.",
    }
  },
  {
    id:2, stage:1, stageTitle:"Foundations",
    title:"Montages: Referential vs. Bipolar",
    concept:"How you wire the channels shapes what you see.",
    body:"Referential: each electrode vs. a common reference — shows true waveform shape. Bipolar: adjacent electrodes compared in a chain — localises by phase reversal. The same brain activity looks completely different in each montage.",
    keyPoints:["Phase reversal in bipolar = source location","Referential shows true morphology","Same EEG looks different in each montage"],
    imageNote:"Same focal spike looks different in referential vs. bipolar.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"In a bipolar chain, a phase reversal at T4 means:",
      options:["T4 has a bad electrode","The discharge maximum is at T4"],
      answer:1,
      verdict:"Phase reversal = source",
      subtitle:"The two channels flanking the maximum deflect in opposite directions.",
      why:"In a bipolar montage, when adjacent channel pairs point away from each other, the electrode between them is closest to the generator. This is the phase reversal — and it localises the source.",
      mistake:"Thinking phase reversal means artifact. A bad electrode causes a spike on ONE channel only, with no logical field.",
    }
  },
  {
    id:3, stage:1, stageTitle:"Foundations",
    title:"EEG Frequency Bands",
    concept:"Frequency is the first axis of interpretation.",
    body:"Delta <4 Hz · Theta 4–8 Hz · Alpha 8–13 Hz · Beta >13 Hz.\nAlpha is the dominant rhythm of a relaxed awake adult with eyes closed. Delta in an awake adult is always abnormal. Excess beta suggests benzodiazepines or barbiturates.",
    keyPoints:["Delta in awake adults = always abnormal","Alpha blocks with eye opening","Excess beta = medications (benzodiazepines, barbiturates)"],
    imageNote:"Live: normal awake EEG — alpha maximal at O1/O2.",
    imageCredit:"PhysioNet EEG Motor Movement/Imagery Dataset (open access)",
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel showing the strongest alpha rhythm.",
      target:["O1","O2"],
      verdict:"Occipital alpha",
      subtitle:"O1 and O2 — the posterior dominant rhythm.",
      why:"Alpha is maximal at the occipital poles. The regular ~10 Hz sinusoidal activity at O1/O2 contrasts with the lower-amplitude, irregular activity at frontal leads.",
      mistake:"Looking at frontal channels. Alpha is a posterior rhythm — frontal channels show beta.",
    }
  },
  {
    id:4, stage:1, stageTitle:"Foundations",
    title:"Normal Awake Adult EEG",
    concept:"Know normal before you can recognise abnormal.",
    body:"Normal adult EEG: posterior dominant rhythm (PDR) 8–13 Hz, well-organised symmetric background, alpha attenuates with eye opening, no epileptiform activity. PDR asymmetry >1 Hz is suspicious for ipsilateral pathology.",
    keyPoints:["PDR 8–13 Hz, posterior, attenuates with eyes open","<1 Hz PDR asymmetry is normal","Anterior low-amplitude beta is normal in alert adults"],
    imageNote:"Live: normal adult awake EEG.",
    imageCredit:"PhysioNet EEG Motor Movement/Imagery Dataset (open access)",
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel carrying the posterior dominant rhythm.",
      target:["O1","O2"],
      verdict:"Posterior dominant rhythm",
      subtitle:"The most important single feature of the normal EEG.",
      why:"The PDR is maximal at the occipital electrodes. In a normal awake adult it sits between 8–13 Hz and is everything else is relatively quiet by comparison.",
      mistake:"Reporting a PDR of 7 Hz as normal in an adult. The lower limit is 8 Hz — anything slower deserves attention.",
    }
  },
  {
    id:5, stage:1, stageTitle:"Foundations",
    title:"Drowsiness & Stage 1 Sleep",
    concept:"The transition from wakefulness changes everything.",
    body:"In drowsiness: PDR slows and becomes intermittent, anterior theta appears, vertex sharp waves emerge at Cz. RMTD — rhythmic temporal theta of drowsiness — is a benign pattern often misread as seizure.",
    keyPoints:["PDR slows in drowsiness — don't over-interpret","V-waves at Cz are normal Stage 1 features","RMTD is benign — sharp theta bursts at temporal in drowsiness"],
    imageNote:"Live: drowsy EEG with vertex sharps and anterior theta.",
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Watch C3 and C4. Vertex sharp waves appear every few seconds — large centrally-maximal negative deflections.",
      verdict:"Vertex sharp waves",
      subtitle:"Physiological events of Stage 1 sleep.",
      why:"Vertex sharp waves are normal Stage 1 sleep transients. They have no afterdischarge, are symmetric at the vertex, and look nothing like a focal spike in context. Don't call them epileptiform.",
      mistake:"Calling vertex sharps epileptiform. The key: they are symmetric, maximal at Cz, and lack an aftergoing slow wave.",
    }
  },
  {
    id:6, stage:1, stageTitle:"Foundations",
    title:"Stage 2 Sleep: Spindles & K-complexes",
    concept:"Sleep spindles and K-complexes define Stage 2.",
    body:"Spindles: 11–16 Hz waxing-waning bursts, 0.5–2 s, maximal Cz. K-complexes: high-amplitude biphasic waves at Cz, often followed by a spindle. Both are normal. Asymmetric spindles → suspect thalamic pathology.",
    keyPoints:["Spindles: 11–16 Hz, waxing-waning, maximal Cz","K-complexes: biphasic, vertex, often stimulus-evoked","Asymmetric spindles → thalamic lesion"],
    imageNote:"Live: Stage 2 sleep with spindles and K-complexes.",
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Watch C3 and C4 for spindles — waxing-waning fast bursts — and K-complexes — sudden large biphasic waves.",
      verdict:"Spindles + K-complexes",
      subtitle:"Thalamocortical signatures of Stage 2 NREM.",
      why:"Spindles are generated by thalamocortical circuits and confirm Stage 2. If you see them only on one side, suspect a thalamic lesion ipsilateral to their absence.",
      mistake:"Calling the fast spindle activity 'fast ictal activity.' Spindles are waxing-waning — ictal fast activity builds and doesn't show this symmetric envelope.",
    }
  },
  {
    id:7, stage:1, stageTitle:"Foundations",
    title:"Sensitivity, Filters & Calibration",
    concept:"Your settings are part of your interpretation.",
    body:"Standard gain: 7 µV/mm. Low-frequency filter (LFF) at 1 Hz removes drift. High-frequency filter (HFF) at 70 Hz removes muscle artifact. Notch filter removes 50/60 Hz line noise. Raising the LFF eliminates slow waves — always check settings before interpreting delta activity.",
    keyPoints:["Standard sensitivity: 7 µV/mm","HFF at 70 Hz removes gamma and muscle","LFF at 1 Hz removes drift — but also cuts delta if set too high"],
    imageNote:"Same segment at different sensitivity settings.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"The LFF is set to 5 Hz. What activity has been removed?",
      options:["Beta and gamma (fast activity)","Delta and theta (slow activity below 5 Hz)"],
      answer:1,
      verdict:"Delta and theta removed",
      subtitle:"The LFF cuts everything below its cutoff frequency.",
      why:"Raising the low-frequency filter eliminates frequencies below its cutoff. At 5 Hz, all delta and most theta disappear — including any genuine pathological slowing.",
      mistake:"Forgetting to check filter settings before interpreting slow activity. Always verify before calling delta 'encephalopathy.'",
    }
  },
  {
    id:8, stage:1, stageTitle:"Foundations",
    title:"Pediatric EEG: Age Matters",
    concept:"The normal EEG is a moving target in childhood.",
    body:"PDR matures from ~3 Hz at 3 months to ~10 Hz by age 15. Delta is normal in young children. Hypnagogic hypersynchrony — high-amplitude 3–5 Hz rhythmic activity in drowsiness — is normal under age 5. Always interpret pediatric EEGs against age-normative data.",
    keyPoints:["PDR matures from 3 Hz (3 months) to 10 Hz (15 years)","Hypnagogic hypersynchrony is normal <5 years","Delta in young children can be normal — consider age"],
    imageNote:"Live: normal 5-year-old EEG — higher amplitude, more theta, slower PDR.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A 3-year-old has a PDR of 7 Hz. Is this abnormal?",
      options:["Yes — 7 Hz is too slow, suggests epilepsy","No — 7 Hz is normal for age 3"],
      answer:1,
      verdict:"Normal for age",
      subtitle:"PDR matures gradually through childhood.",
      why:"At age 3, a PDR of 7–8 Hz is entirely within normal limits. The same finding in a 20-year-old would indicate abnormal background slowing. Paediatric EEG always requires age-matched interpretation.",
      mistake:"Applying adult norms to children. This is one of the most consequential errors in clinical EEG.",
    }
  },

  // ── STAGE 2: NORMAL VARIANTS ─────────────────────────────────────────────
  {
    id:9, stage:2, stageTitle:"Normal Variants",
    title:"Wicket Waves",
    concept:"The most commonly over-read benign pattern.",
    body:"Wicket waves: monophasic, arciform, 6–11 Hz, maximal mid-temporal, during drowsiness. Key: they are monophasic — no aftergoing slow wave — and appear in runs, not in isolation. Not epileptiform.",
    keyPoints:["Monophasic = no afterdischarge (the critical distinction)","Appear in runs, temporal distribution","Common source of false epilepsy diagnoses"],
    imageNote:"Live: wicket waves in temporal leads during drowsiness.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel where wicket waves are maximal.",
      target:["T3","T4"],
      verdict:"Benign variant",
      subtitle:"No after-going slow wave.",
      why:"Wicket waves are a normal variant seen during drowsiness. They are monophasic — each arc ends cleanly without a following slow wave. That absence is what makes them benign.",
      mistake:"Mistaking wicket waves for epileptiform discharges. The rule: monophasic + temporal + runs + drowsiness = wicket waves.",
    }
  },
  {
    id:10, stage:2, stageTitle:"Normal Variants",
    title:"14 and 6 Hz Positive Spikes",
    concept:"Dramatic-looking. No clinical significance.",
    body:"Comb-like bursts at 14 Hz and/or 6 Hz, posterior temporal, during drowsiness. Surface-positive polarity — unlike epileptiform discharges which are surface-negative. Found in 20–60% of normal adolescents.",
    keyPoints:["Surface-positive polarity — key distinguishing feature","Maximal posterior temporal, drowsiness/early sleep","Found in up to 60% of normal adolescents"],
    imageNote:"14 and 6 Hz positive bursts during drowsiness.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"14 and 6 Hz positive spikes are surface-positive. Why does polarity matter?",
      options:["It doesn't — polarity is irrelevant","Most epileptiform discharges are surface-negative, so positivity argues against pathology"],
      answer:1,
      verdict:"Polarity is diagnostic",
      subtitle:"Surface-positive = almost always benign.",
      why:"True epileptiform IEDs are surface-negative by convention. Surface-positive sharp transients in the right context — temporal, during drowsiness, comb-like — are almost invariably benign.",
      mistake:"Reporting 14+6 spikes as epileptiform. Their surface-positive polarity, comb morphology, and drowsy state should prevent this.",
    }
  },
  {
    id:11, stage:2, stageTitle:"Normal Variants",
    title:"RMTD — Rhythmic Midtemporal Theta of Drowsiness",
    concept:"Looks exactly like a seizure. Isn't.",
    body:"RMTD: sharply contoured, notched theta (5–7 Hz) bursts at midtemporal electrodes in drowsiness. Mimics temporal lobe seizure onset. Key difference: RMTD does not evolve — same frequency, same field, abrupt start and stop. No clinical correlate.",
    keyPoints:["Theta bursts in temporal region during drowsiness","Does NOT evolve — frequency and field stay fixed","Sharply notched morphology is the trap"],
    imageNote:"Live: drowsy EEG — watch temporal leads for RMTD-like theta bursts.",
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Watch T3/T4. Notice theta bursts that appear and stop without changing frequency or spreading.",
      verdict:"No evolution = not a seizure",
      subtitle:"RMTD starts and stops at a fixed frequency.",
      why:"A temporal lobe seizure starts fast, builds in amplitude, shifts in frequency, and spreads. RMTD just appears and disappears at the same frequency. The absence of evolution is the critical differentiator.",
      mistake:"Treating RMTD as NCSE. Unnecessary IV benzodiazepines have been given because of this mistake.",
    }
  },
  {
    id:12, stage:2, stageTitle:"Normal Variants",
    title:"Small Sharp Spikes (BSSS)",
    concept:"Tiny, fleeting, and harmless.",
    body:"SSS (benign sporadic sleep spikes): <50 µV, <50 ms, monophasic or biphasic, NREM sleep only. Disappear during REM and wakefulness. No aftergoing slow wave. The combination of small size, brevity, and NREM-only occurrence defines them as benign.",
    keyPoints:["<50 µV amplitude, <50 ms duration","NREM sleep only — disappear in wakefulness and REM","No aftergoing slow wave"],
    imageNote:"Small sharp spike during Stage 2 sleep — compare amplitude to background.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A 45 ms, <30 µV monophasic transient in NREM sleep with no afterdischarge is:",
      options:["A temporal epileptiform discharge","A benign small sharp spike"],
      answer:1,
      verdict:"Benign small sharp spike",
      subtitle:"Small, brief, NREM-only, no afterdischarge.",
      why:"All criteria for SSS are met: brief (<50 ms), small (<50 µV), NREM-only, monophasic, no afterdischarge. These are benign and should not be reported as epileptiform.",
      mistake:"Calling them temporal IEDs based on location alone. Amplitude, duration, and sleep stage together define SSS.",
    }
  },
  {
    id:13, stage:2, stageTitle:"Normal Variants",
    title:"SREDA",
    concept:"The rare variant most readers have never seen — until they diagnose a seizure incorrectly.",
    body:"SREDA: sustained rhythmic theta (5–7 Hz) or alpha, bilateral parieto-temporal, in an awake asymptomatic patient. Lasts 20 s to several minutes. No clinical correlate, no post-ictal slowing. Seen during hyperventilation.",
    keyPoints:["Bilateral sustained theta/alpha during wakefulness","Patient asymptomatic — no clinical correlate","No post-ictal slowing — the key seizure indicator"],
    imageNote:"SREDA: sudden-onset bilateral theta, no symptoms, no post-ictal slowing.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Sustained bilateral 6 Hz theta in an awake, asymptomatic patient with no post-ictal slowing — treat for NCSE?",
      options:["Yes — bilateral rhythmic activity requires treatment","No — this is SREDA, a benign normal variant"],
      answer:1,
      verdict:"SREDA — benign",
      subtitle:"Asymptomatic + no post-ictal slowing = not a seizure.",
      why:"SREDA is one of the most important normal variants to know. The patient is asymptomatic during it and there is no post-ictal change — both are incompatible with NCSE.",
      mistake:"Treating SREDA as NCSE exposes the patient to unnecessary IV benzodiazepines and ICU admission.",
    }
  },

  // ── STAGE 3: ARTIFACTS ────────────────────────────────────────────────────
  {
    id:14, stage:3, stageTitle:"Artifacts",
    title:"Eye Blink & Eye Movement Artifacts",
    concept:"The eyes are generators, not just bystanders.",
    body:"The cornea is positive relative to the retina. Blinking: symmetric bifrontal negative deflection. Lateral eye movements: opposite polarity at Fp1 vs Fp2. Most common artifact in clinical EEG.",
    keyPoints:["Bifrontal distribution (Fp1, Fp2, F3, F4)","Blinks: symmetric bilateral negative deflection","Lateral eye movements: opposite polarity at Fp1 vs Fp2"],
    imageNote:"Live: eye blink artifact — watch the frontal leads.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap where the eye blink artifact is largest.",
      target:["Fp1","Fp2"],
      verdict:"Frontopolar artifact",
      subtitle:"The corneoretinal dipole projects most strongly to Fp1/Fp2.",
      why:"Blink artifacts are maximal at the frontal poles, closest to the eyes. The large bifrontal deflections attenuate rapidly posteriorly — confirming they are not cerebral.",
      mistake:"Calling blinks 'frontal slow waves' or 'frontal IEDs.' Ask the patient to close their eyes: blinks stop; cerebral activity continues.",
    }
  },
  {
    id:15, stage:3, stageTitle:"Artifacts",
    title:"Muscle (EMG) Artifact",
    concept:"The brain's noisiest impostor.",
    body:"Muscle artifact: high-frequency (>30 Hz), irregular, low amplitude per wave. Lateral/temporal predominance — the temporalis muscle. Worsens with anxiety, jaw clenching. Ask the patient to relax the jaw to confirm.",
    keyPoints:["High frequency (>30 Hz), irregular, low amplitude","Lateral/temporal predominance (temporalis muscle)","Jaw relaxation resolves it immediately"],
    imageNote:"Live: muscle burst at temporal electrodes — watch T3/T4.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel most contaminated by muscle artifact.",
      target:["T3","T4"],
      verdict:"Temporalis EMG",
      subtitle:"T3 and T4 overlie the temporalis muscle.",
      why:"The high-frequency irregular burst at T3/T4 is EMG from the temporalis muscle, not cerebral activity. A jaw clench creates it; jaw relaxation resolves it immediately.",
      mistake:"Calling temporal muscle burst 'fast ictal activity.' Ictal activity evolves and has a field; muscle artifact stops abruptly with jaw relaxation.",
    }
  },
  {
    id:16, stage:3, stageTitle:"Artifacts",
    title:"Cardiac (EKG) Artifact",
    concept:"A regular rhythm that isn't cerebral.",
    body:"Cardiac artifact: regular, periodic sharp deflections time-locked to QRS. Maximal where the heart's electrical vector intersects the scalp — typically temporal or vertex. Its completely regular interval distinguishes it from epileptiform activity.",
    keyPoints:["Regular rhythm = cardiac — not epileptiform","Check against simultaneously recorded EKG channel","Temporal or vertex — correlates with electrode-vessel proximity"],
    imageNote:"Live: cardiac artifact — regular sharp spikes at 75 bpm.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel where cardiac artifact is most prominent.",
      target:["T3","T4"],
      verdict:"Cardiac artifact",
      subtitle:"Mechanically regular — no cerebral discharge is this precise.",
      why:"Cardiac artifact is most prominent near neck vessels — typically T3 or T4. Its perfectly regular interval matching the heart rate is diagnostic. No epileptiform discharge fires this predictably.",
      mistake:"Calling the regular sharp deflections 'LPDs.' LPDs have variable morphology and slightly irregular periodicity; cardiac artifact is metronomic.",
    }
  },
  {
    id:17, stage:3, stageTitle:"Artifacts",
    title:"Sweat & Slow Artifacts",
    concept:"Very slow waves that aren't delta.",
    body:"Sweat artifact: <0.5 Hz, undulating, high-amplitude, diffuse — from galvanic skin response at electrode sites. Glossokinetic artifact: frontal, rhythmic, linked to tongue movement. Raising the LFF (e.g., to 1–2 Hz) reveals underlying activity.",
    keyPoints:["Sweat: <0.5 Hz, undulating, diffuse, resolves with drying","Glossokinetic: frontal, linked to tongue/speech movements","Raising LFF reveals what's underneath"],
    imageNote:"Sweat artifact: wide sinusoidal baseline drift across multiple channels.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Diffuse very slow (<0.5 Hz) undulating baseline across all channels — is this encephalopathy?",
      options:["Yes — report as diffuse delta slowing","No — this is sweat artifact"],
      answer:1,
      verdict:"Sweat artifact",
      subtitle:"Too slow to be delta — this is galvanic skin response.",
      why:"Sweat artifact is too slow (<0.5 Hz) to be delta (0.5–4 Hz). It affects all channels diffusely and resolves by drying the scalp or cooling the room. Never interpret it as pathological slowing.",
      mistake:"Reporting sweat artifact as 'diffuse delta' — a finding that would prompt urgent clinical workup unnecessarily.",
    }
  },
  {
    id:18, stage:3, stageTitle:"Artifacts",
    title:"60 Hz Noise & Electrode Pops",
    concept:"The environment intrudes on your recording.",
    body:"60 Hz noise: constant, perfectly regular, high-frequency. Single-channel = high-impedance electrode. Widespread = environmental. Electrode pop: single-channel high-amplitude fast transient from momentary contact loss. True cerebral discharges always spread to neighbours.",
    keyPoints:["60 Hz noise: single-channel = electrode; widespread = environment","Electrode pop: single channel, asymmetric rise-fall","True discharges spread to adjacent channels"],
    imageNote:"60 Hz artifact on single channel (impedance) vs. diffuse (environmental).",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A sharp transient appears only at F8, with nothing on any adjacent electrode. This is:",
      options:["A focal F8 epileptiform discharge","An electrode artifact — true discharges always spread"],
      answer:1,
      verdict:"Electrode artifact",
      subtitle:"True discharges always have a field.",
      why:"Any single-channel transient with no neighbouring projection is an artifact until proven otherwise. True cerebral discharges cannot be confined to one electrode — they always project to adjacent channels.",
      mistake:"Reporting a single-channel transient as a 'right frontotemporal spike.' Checking the field (adjacent channels) must come before any epileptiform call.",
    }
  },

  // ── STAGE 4: PATHOLOGICAL PATTERNS ───────────────────────────────────────
  {
    id:19, stage:4, stageTitle:"Pathological Patterns",
    title:"Spikes and Sharp Waves: Criteria",
    concept:"Knowing the criteria prevents both over- and under-diagnosis.",
    body:"Spike: 20–70 ms, surface-negative, disrupts background, has aftergoing slow wave. Sharp wave: same but 70–200 ms. Both must have a plausible field (spread to neighbours). An isolated sharp transient without these features is not epileptiform.",
    keyPoints:["Spike: 20–70 ms; sharp wave: 70–200 ms","Must have aftergoing slow wave and disrupt background","Must have a plausible field across adjacent electrodes"],
    imageNote:"Live: focal temporal spike — watch T3.",
    imageCredit:"Temple University EEG Corpus (TUAB) — open access",
    interaction:{
      type:"observe",
      prompt:"Watch T3. Each time a spike fires, look for the slow wave that follows it.",
      verdict:"Aftergoing slow wave = epileptiform",
      subtitle:"The slow wave is the defining criterion.",
      why:"The aftergoing slow wave is what separates an epileptiform discharge from any sharp transient. No slow wave = not a spike, no matter how pointed or prominent.",
      mistake:"Calling any sharp transient a 'spike' without checking for the afterdischarge. This single mistake is responsible for most over-diagnoses.",
    }
  },
  {
    id:20, stage:4, stageTitle:"Pathological Patterns",
    title:"Focal Interictal Epileptiform Discharges",
    concept:"Where is it? How often? What context?",
    body:"Focal IEDs indicate focal cortical irritability. Localisation guides surgical planning. Common syndromes: temporal (TLE), frontal (FLE), centrotemporal (Rolandic). Frequency correlates loosely but imperfectly with seizure burden.",
    keyPoints:["Temporal IEDs: most common focal epilepsy pattern","Centrotemporal (Rolandic) spikes: benign childhood epilepsy","Always report lateralisation, localisation, and frequency"],
    imageNote:"Live: left temporal spike with T3 phase reversal.",
    imageCredit:"Temple University EEG Corpus (TUAB) — open access",
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel at the centre of the discharge (phase reversal point).",
      target:["T3"],
      verdict:"Left temporal IED",
      subtitle:"T3 is the epicentre of this discharge.",
      why:"T3 is the source of this left temporal IED. In a bipolar montage, the channels above and below T3 would point away from each other — the classic phase reversal confirming the source location.",
      mistake:"Calling the whole left hemisphere abnormal because multiple channels show the discharge. The focus is T3 — the others show field spread.",
    }
  },
  {
    id:21, stage:4, stageTitle:"Pathological Patterns",
    title:"Generalised Epileptiform Discharges",
    concept:"Both hemispheres, simultaneously.",
    body:"Classic 3 Hz spike-wave: bilateral synchronous, frontal predominance, abrupt onset/offset, associated with absence. Polyspike-wave → juvenile myoclonic epilepsy. Slow spike-wave (<2.5 Hz) → Lennox-Gastaut syndrome.",
    keyPoints:["3 Hz spike-wave: absence epilepsy, frontal predominance","Polyspike-wave: JME pattern","Slow (<2.5 Hz) spike-wave: Lennox-Gastaut"],
    imageNote:"Live: 3 Hz generalised spike-wave in bursts.",
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Count the spike-wave complexes over any 3-second window during a burst.",
      verdict:"3 Hz generalised spike-wave",
      subtitle:"Bilateral, synchronous, frontal-predominant.",
      why:"You should count approximately 9 complexes in 3 seconds, confirming the 3 Hz rate. The bursts start and stop abruptly, are bilateral with frontal predominance, and the background is flat between bursts — classic absence.",
      mistake:"Calling slow (<2.5 Hz) generalised spike-wave 'absence' in a child. Slow spike-wave means Lennox-Gastaut, a much more severe syndrome.",
    }
  },
  {
    id:22, stage:4, stageTitle:"Pathological Patterns",
    title:"Focal Delta Slowing",
    concept:"Slow waves tell you where the problem is.",
    body:"Focal polymorphic delta over one region = structural lesion until proven otherwise. Rhythmic focal delta can be ictal — look for evolution. Correlate with imaging. Focal theta may indicate subcortical white matter dysfunction.",
    keyPoints:["Focal polymorphic delta = structural lesion until proven otherwise","Rhythmic focal delta can be ictal — look for evolution","Get imaging when focal slowing is unexplained"],
    imageNote:"Live: continuous left temporal polymorphic delta.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel with the most prominent slow activity.",
      target:["T3","F3","C3"],
      verdict:"Left temporal focal delta",
      subtitle:"Structural lesion until proven otherwise.",
      why:"The slow activity is maximal over the left hemisphere (T3, F3, C3). Focal polymorphic delta means there is a structural problem in the underlying cortex — imaging is mandatory.",
      mistake:"Attributing focal delta to 'postictal slowing' without evidence of a preceding seizure. Always get imaging for unexplained focal slowing.",
    }
  },
  {
    id:23, stage:4, stageTitle:"Pathological Patterns",
    title:"Periodic Discharges",
    concept:"Repetition with a rhythm — a dangerous sign.",
    body:"Lateralised periodic discharges (LPDs): one hemisphere, regular ~1 Hz, acute focal injury + high seizure risk. Generalised periodic discharges (GPDs): bilateral — anoxic injury, metabolic, prion disease. LPDs = ictal-interictal continuum.",
    keyPoints:["LPDs = acute focal injury + high seizure risk","GPDs = anoxic injury, metabolic, prion disease","Ictal-interictal continuum — correlate clinically"],
    imageNote:"Live: LPDs — regular 1 Hz sharp-slow over right hemisphere.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the hemisphere where the periodic discharges are maximal.",
      target:["Fp2","F4","C4","T4","O2"],
      verdict:"Right hemisphere LPDs",
      subtitle:"Ictal-interictal continuum — urgent evaluation needed.",
      why:"All the periodic activity is on the right (even-numbered channels). The combination of lateralisation and 1 Hz periodicity places this firmly in the ictal-interictal continuum. Continuous EEG monitoring is needed.",
      mistake:"Dismissing LPDs as 'just artifact' because they're too regular. Regularity is the point — it means periodically recurring discharge from a focal injury.",
    }
  },

  // ── STAGE 5: SEIZURE RECOGNITION ─────────────────────────────────────────
  {
    id:24, stage:5, stageTitle:"Seizure Recognition",
    title:"What Makes a Seizure on EEG",
    concept:"Evolution is the hallmark.",
    body:"A seizure: rhythmic activity that evolves in frequency, amplitude, and spatial distribution. Has a clear onset and offset. Post-ictal slowing (delta) confirms and lateralises. Without evolution, a pattern is not a seizure.",
    keyPoints:["Evolution in frequency, amplitude, and field = ictal","Post-ictal slowing confirms seizure onset zone","No evolution = not a seizure (RMTD? SREDA?)"],
    imageNote:"Live: temporal lobe seizure — theta onset evolving to alpha then slowing.",
    imageCredit:"CHB-MIT Scalp EEG Database (PhysioNet, open access)",
    interaction:{
      type:"observe",
      prompt:"Watch for the seizure beginning at T3 (~4 s in). Notice how the activity changes frequency and amplitude over time.",
      verdict:"Ictal — evolution confirmed",
      subtitle:"Frequency, amplitude, and field all change over time.",
      why:"The seizure starts as low-amplitude theta at T3, builds in amplitude, shifts frequency, then slows into post-ictal delta. Evolution across all three dimensions — frequency, amplitude, field — is what makes it ictal.",
      mistake:"Calling RMTD a seizure because it looks like an ictal onset. RMTD starts and stops without any evolution — that is the critical distinction.",
    }
  },
  {
    id:25, stage:5, stageTitle:"Seizure Recognition",
    title:"Temporal Lobe Seizure",
    concept:"The most common focal seizure in adults.",
    body:"TLE: focal onset at anterior temporal electrode, rhythmic theta → alpha build, spread to ipsilateral hemisphere, possible secondary generalisation. Post-ictal unilateral slowing helps lateralise the seizure onset zone.",
    keyPoints:["Onset: focal rhythmic theta at anterior temporal","Builds, slows, spreads — classic evolution","Post-ictal unilateral slowing helps lateralise"],
    imageNote:"Live: left temporal lobe seizure evolving from T3.",
    imageCredit:"CHB-MIT Scalp EEG Database (PhysioNet, open access)",
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel where the seizure originates.",
      target:["T3"],
      verdict:"Left temporal onset",
      subtitle:"T3 — left anterior temporal.",
      why:"The seizure starts at T3 and spreads to C3, then F3, then contralateral T4. This propagation pattern is the canonical left TLE signature. Post-ictal slowing at T3 confirms the onset zone.",
      mistake:"Tapping T4 because the right side eventually shows activity. Secondary spread does not mean bilateral onset — track where the activity starts, not where it ends up.",
    }
  },
  {
    id:26, stage:5, stageTitle:"Seizure Recognition",
    title:"Generalised Tonic-Clonic Seizure",
    concept:"The full storm — from background to cessation.",
    body:"GTC on EEG: tonic phase → high-amplitude diffuse fast activity. Clonic phase → rhythmic spike-wave slowing from 5 Hz → 2.5 Hz. Post-ictal suppression → diffuse flat trace for seconds to minutes. Post-ictal suppression is highly specific for a true GTC.",
    keyPoints:["Tonic: high-amplitude fast (>10 Hz)","Clonic: spike-wave bursts that progressively slow","Post-ictal suppression: specific for true GTC"],
    imageNote:"Live: GTC — tonic fast → clonic spike-wave → post-ictal suppression.",
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Watch the full cycle: tonic (fast), then clonic (slowing spike-wave), then suppression (flat trace).",
      verdict:"Generalised tonic-clonic seizure",
      subtitle:"Post-ictal suppression is the diagnostic key.",
      why:"A genuinely flat trace for 20–30 seconds after convulsive activity confirms a true GTC. This pattern never occurs in psychogenic non-epileptic events.",
      mistake:"Missing the post-ictal suppression because the recording ends too early. Always continue recording for several minutes after clinical activity stops.",
    }
  },
  {
    id:27, stage:5, stageTitle:"Seizure Recognition",
    title:"Non-Convulsive Status Epilepticus",
    concept:"The seizure you miss without EEG.",
    body:"NCSE: sustained seizure activity without prominent motor signs. Patterns: continuous spike-wave, rhythmic delta/theta with evolution, or periodic discharges. Patient may be confused, unresponsive, or show only subtle twitching. Medical emergency.",
    keyPoints:["Altered consciousness + no convulsions = do EEG urgently","Continuous or near-continuous epileptiform patterns","Response to IV benzodiazepine — clinical + EEG change — is diagnostic"],
    imageNote:"Live: generalised encephalopathy — recognise what needs urgent treatment.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Continuous spike-wave in an unresponsive patient post-convulsion — immediate action?",
      options:["Wait and observe — this may resolve","Treat as NCSE — IV benzodiazepine + urgent neurology"],
      answer:1,
      verdict:"Treat immediately",
      subtitle:"NCSE is a neurological emergency.",
      why:"Every minute of ongoing seizure activity causes neuronal injury. IV benzodiazepine, continuous EEG monitoring, and urgent neurology consultation are the standard response.",
      mistake:"Waiting for more convulsive activity before treating. The whole point of NCSE is that the seizure has already lost its motor component — EEG is the only window.",
    }
  },

  // ── STAGE 6: CLINICAL INTEGRATION ────────────────────────────────────────
  {
    id:28, stage:6, stageTitle:"Clinical Integration",
    title:"Diffuse Encephalopathy Patterns",
    concept:"The whole brain speaks when it is diffusely disturbed.",
    body:"Diffuse encephalopathy: generalised slowing (alpha → theta → delta), loss of normal architecture, triphasic waves in hepatic/uremic encephalopathy, suppression-burst in severe anoxia. Triphasic waves can mimic NCSE — clinical context is essential.",
    keyPoints:["Background slowing = severity of encephalopathy","Triphasic waves: bifrontal, phase-lag, metabolic context","Suppression-burst: severe — anoxia, barbiturates, hypothermia"],
    imageNote:"Live: triphasic waves — bifrontal, 1.8 Hz, on a slow background.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the region where triphasic waves are most prominent.",
      target:["Fp1","Fp2","F3","F4"],
      verdict:"Frontal triphasic waves",
      subtitle:"Bifrontal, 1.8 Hz, anterior-to-posterior phase lag.",
      why:"Triphasic waves have frontal predominance with an anterior-to-posterior phase lag — the frontal deflection leads the posterior by milliseconds. This spatial pattern, in a metabolic context, distinguishes them from NCSE.",
      mistake:"Treating triphasic waves as NCSE without clinical context. Metabolic encephalopathy + bifrontal phase-lag = triphasics; treat the metabolic cause.",
    }
  },
  {
    id:29, stage:6, stageTitle:"Clinical Integration",
    title:"Common Interpretive Errors",
    concept:"Knowing where to be wrong is half of being right.",
    body:"Most common misinterpretations: wicket waves called epileptiform, RMTD called seizure, muscle artifact called fast ictal activity, eye blinks called frontal IEDs, SSS called temporal spikes, drowsiness changes called encephalopathy. The antidote: strict criteria + clinical context.",
    keyPoints:["Always apply strict morphological criteria","Context (age, state, clinical history) shapes interpretation","When uncertain: describe the finding, note uncertainty — do not over-diagnose"],
    imageNote:"Live: wicket waves — the most commonly over-read pattern.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Runs of monophasic 8 Hz temporal sharps during drowsiness, no afterdischarge — epileptiform?",
      options:["Yes — report as right temporal IEDs","No — wicket waves, a benign normal variant"],
      answer:1,
      verdict:"Benign variant — not epileptiform",
      subtitle:"Monophasic + temporal + runs + no afterdischarge = wicket waves.",
      why:"This is the most consequential over-read in EEG. Wicket waves cause unnecessary epilepsy diagnoses, driving-licence loss, and antiseizure medication exposure. The criteria are strict — apply them.",
      mistake:"The mistake is the first option. This error has real consequences for patients. Monophasic + runs + temporal + drowsiness = wicket waves, every time.",
    }
  },
  {
    id:30, stage:6, stageTitle:"Clinical Integration",
    title:"Clinical Correlation: The Final Principle",
    concept:"EEG is a test. A test needs a context.",
    body:"The same pattern means different things in different patients. Always integrate: age, clinical history, reason for referral, medications, recording state. A good report synthesises findings with the clinical question — it doesn't just list patterns.",
    keyPoints:["Same pattern, different contexts = different diagnoses","Medications (benzodiazepines, AEDs) alter EEG","The report conclusion should answer the clinical question"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"3 Hz generalised spike-wave in a 60-year-old with acute confusion — childhood absence epilepsy?",
      options:["Yes — the pattern is classic for absence","No — in a confused adult, this is NCSE until proven otherwise"],
      answer:1,
      verdict:"NCSE in an adult",
      subtitle:"Context transforms interpretation completely.",
      why:"Absence epilepsy is a childhood syndrome. The same 3 Hz pattern in a confused adult is NCSE — a medical emergency requiring immediate treatment. The waveform is identical; the diagnosis is opposite.",
      mistake:"Diagnosing absence epilepsy in an adult based on the waveform alone, without considering age and clinical state.",
    }
  },
  {
    id:31, stage:6, stageTitle:"Full Cap Foundations",
    title:"Nasion and Inion",
    concept:"The 10-20 map starts from reliable landmarks.",
    body:"The front-back head measurement starts at the nasion and ends at the inion.",
    keyPoints:["Nasion = bridge of nose","Inion = bony back point","Measurements make placement reproducible"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"The front-to-back measurement starts at:",
      options:["Temple to temple","Nose bridge to back bump"],
      answer:1,
      verdict:"Nose bridge to back bump",
      subtitle:"Nasion to inion.",
      why:"Those landmarks are easy to find on different patients.",
      mistake:"Starting the map from a vague hairline or face shape.",
    }
  },
  {
    id:32, stage:6, stageTitle:"Full Cap Foundations",
    title:"Preauricular Points",
    concept:"The side-to-side measurement uses points near the ears.",
    body:"The second main measurement runs from one preauricular point to the other.",
    keyPoints:["Preauricular = just in front of each ear","This anchors left-right placement","The map needs front-back and side-side lines"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"The side-to-side measurement uses points near the:",
      options:["Eyes","Ears"],
      answer:1,
      verdict:"Ears",
      subtitle:"Preauricular points sit just before each ear.",
      why:"These points anchor the left-right line across the head.",
      mistake:"Using the eyes as the side-to-side anchor.",
    }
  },
  {
    id:33, stage:6, stageTitle:"Full Cap Foundations",
    title:"10 and 20",
    concept:"The numbers come from measurement increments.",
    body:"The 10-20 system divides head distances into 10% and 20% steps.",
    keyPoints:["Measure the head","Mark percentages","Place sensors at intersections"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"In 10-20, the 10 and 20 are:",
      options:["Channel counts","Measurement percentages"],
      answer:1,
      verdict:"Measurement percentages",
      subtitle:"The map is built from measured distances.",
      why:"Marks are placed at 10% and 20% intervals.",
      mistake:"Treating 10-20 as just a list of sensor names.",
    }
  },
  {
    id:34, stage:6, stageTitle:"Full Cap Foundations",
    title:"Intersections",
    concept:"Sensors go where measured lines cross.",
    body:"Front-back, side-side, circumferential, and transverse marks create sensor positions.",
    keyPoints:["Lines are measured","Crossings become sensor spots","This makes the cap reproducible"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Watch how measured lines create sensor positions.",
      verdict:"Measured crossings",
      subtitle:"The cap is a map, not a guess.",
      why:"Electrodes are placed where measured head-map lines intersect.",
      mistake:"Thinking sensors are placed by eye.",
    }
  },
  {
    id:35, stage:6, stageTitle:"Full Cap Foundations",
    title:"Near the Middle",
    concept:"Lower numbers tend to sit closer to the midline.",
    body:"C4 is closer to the middle than T8 because the number is lower.",
    keyPoints:["Numbers give side","Lower often means nearer middle","Far lateral names have higher numbers"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Which is closer to the middle?",
      options:["T8","C4"],
      answer:1,
      verdict:"C4",
      subtitle:"Lower numbers tend to sit nearer the midline.",
      why:"T8 is farther out on the side of the head.",
      mistake:"Using number only for left-right and missing distance from middle.",
    }
  },
  {
    id:36, stage:6, stageTitle:"Full Cap Foundations",
    title:"The Z Line",
    concept:"Z marks the center line.",
    body:"Midline electrodes use z because they sit on neither left nor right.",
    keyPoints:["z = zero/midline","Fz, Cz, Pz sit in the middle","Midline is a reference line"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Cz sits on the:",
      options:["Right side","Middle line"],
      answer:1,
      verdict:"Middle line",
      subtitle:"z means the midline.",
      why:"Midline sensors are neither odd-left nor even-right.",
      mistake:"Reading z as a side number.",
    }
  },
  {
    id:37, stage:6, stageTitle:"Display Basics",
    title:"Channel",
    concept:"A channel is one displayed comparison.",
    body:"In EEG, a visible line often shows the difference between two inputs.",
    keyPoints:["Two inputs go in","One line comes out","That line is a channel or derivation"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A channel is best thought of as:",
      options:["The whole cap","One displayed comparison"],
      answer:1,
      verdict:"One displayed comparison",
      subtitle:"Two inputs become one line.",
      why:"The displayed line is the output of a comparison.",
      mistake:"Thinking one channel always means one raw electrode.",
    }
  },
  {
    id:38, stage:6, stageTitle:"Display Basics",
    title:"Chain",
    concept:"A chain links several neighboring comparisons.",
    body:"A temporal chain moves from front to side to back along one path.",
    keyPoints:["Channels can be linked","A linked string is a chain","Chains organize the page"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A chain is:",
      options:["One isolated sensor","A linked row of channels"],
      answer:1,
      verdict:"Linked row of channels",
      subtitle:"The page is organized in chains.",
      why:"A chain lets you follow activity across neighboring sensor pairs.",
      mistake:"Reading each line without noticing its neighbors.",
    }
  },
  {
    id:39, stage:6, stageTitle:"Display Basics",
    title:"Page Layout",
    concept:"The bipolar page has an order.",
    body:"A common display stacks left temporal, left parasagittal, midline, right parasagittal, and right temporal chains.",
    keyPoints:["The page follows the head","Left chains appear together","Right chains appear together"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Watch the page as chains are stacked from left to right.",
      verdict:"Organized page",
      subtitle:"The display mirrors the head map.",
      why:"The chain order helps you locate patterns across the cap.",
      mistake:"Treating the page order as random.",
    }
  },
  {
    id:40, stage:6, stageTitle:"Display Basics",
    title:"ECG Line",
    concept:"A heart channel often appears at the bottom.",
    body:"A separate ECG channel helps compare EEG marks with heartbeat timing.",
    keyPoints:["ECG records heart timing","It helps identify heart artifact","It is not a brain channel"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"The bottom ECG channel helps check:",
      options:["Hair thickness","Heartbeat timing"],
      answer:1,
      verdict:"Heartbeat timing",
      subtitle:"It helps separate brain from heart artifact.",
      why:"Regular EEG marks can be compared with the ECG rhythm.",
      mistake:"Ignoring the ECG line when sharp marks repeat regularly.",
    }
  },
  {
    id:41, stage:6, stageTitle:"Display Basics",
    title:"Average Reference",
    concept:"Another view compares one sensor with the head average.",
    body:"Average reference is different from neighbor-pair display.",
    keyPoints:["Bipolar compares neighbors","Average reference compares to the head average","Both are views, not raw truth"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Average reference compares a sensor with:",
      options:["Only the next sensor","The head average"],
      answer:1,
      verdict:"The head average",
      subtitle:"It is another montage view.",
      why:"Different views can reveal different parts of the same signal.",
      mistake:"Assuming one display view is the only truth.",
    }
  },
  {
    id:42, stage:6, stageTitle:"Display Basics",
    title:"Montage Choice",
    concept:"No view is neutral.",
    body:"Changing the montage can change what is easy or hard to see.",
    keyPoints:["A montage is a display view","Views have strengths","Interpretation starts by knowing the view"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Before interpreting, first check:",
      options:["The patient initials only","The display view"],
      answer:1,
      verdict:"The display view",
      subtitle:"The montage shapes the picture.",
      why:"The same signal can look different in different montages.",
      mistake:"Interpreting a page without knowing how it is displayed.",
    }
  },
  {
    id:43, stage:6, stageTitle:"Eye Artifact",
    title:"Eye Dipole",
    concept:"The eye has a front-positive and back-negative side.",
    body:"The cornea is positive and the retina is negative.",
    keyPoints:["Cornea = front of eye","Retina = back of eye","This creates a dipole"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"The front of the eye is the:",
      options:["Retina","Cornea"],
      answer:1,
      verdict:"Cornea",
      subtitle:"The cornea is relatively positive.",
      why:"Eye movement creates a signal because the eye has polarity.",
      mistake:"Treating eye movement as just mechanical motion.",
    }
  },
  {
    id:44, stage:6, stageTitle:"Eye Artifact",
    title:"Bell Phenomenon",
    concept:"During a blink, the eyes roll upward.",
    body:"That upward movement creates a large frontal signal.",
    keyPoints:["Blink moves the eye upward","Front sensors see it strongly","Both frontal poles can deflect"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A blink is largest near:",
      options:["Back sensors","Front sensors"],
      answer:1,
      verdict:"Front sensors",
      subtitle:"The eyes sit in front.",
      why:"The upward eye movement projects strongly to Fp1 and Fp2.",
      mistake:"Calling a blink a frontal brain wave.",
    }
  },
  {
    id:45, stage:6, stageTitle:"Normal Rhythm",
    title:"Eyes Closed Alpha",
    concept:"Alpha is common during relaxed wakefulness.",
    body:"Alpha is often around 10 per second and strongest posteriorly when eyes are closed.",
    keyPoints:["Awake and relaxed","Eyes closed strengthens alpha","Posterior sensors often show it best"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Alpha is commonly strongest when eyes are:",
      options:["Open and scanning","Closed and relaxed"],
      answer:1,
      verdict:"Closed and relaxed",
      subtitle:"A relaxed eyes-closed state brings it out.",
      why:"Alpha is a normal wakeful rhythm that is often posterior and around 10 Hz.",
      mistake:"Calling normal alpha an abnormal rhythm.",
    }
  },
  {
    id:46, stage:6, stageTitle:"Abnormal Fields",
    title:"Left Temporal Field",
    concept:"A focal discharge has a maximal area.",
    body:"A left temporal abnormality is strongest in the left temporal chain.",
    keyPoints:["Focal means one main area","Temporal means side head","Maximal means strongest"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the left temporal maximum.",
      target:["T3"],
      verdict:"Left temporal maximum",
      subtitle:"T3 sits in the left temporal region.",
      why:"The strongest abnormality is in the left temporal chain.",
      mistake:"Choosing a later spread instead of the maximum field.",
    }
  },
  {
    id:47, stage:6, stageTitle:"Abnormal Fields",
    title:"Right Posterior Field",
    concept:"A field can be strongest at the back-right head.",
    body:"Posterior right activity may be maximal near O2.",
    keyPoints:["Posterior means back","Right uses even numbers","O2 is back-right"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the right posterior maximum.",
      target:["O2"],
      verdict:"Right posterior maximum",
      subtitle:"O2 is the back-right sensor.",
      why:"The maximal field is posterior and right-sided.",
      mistake:"Calling all posterior activity occipital without checking side.",
    }
  },
  {
    id:48, stage:6, stageTitle:"Abnormal Fields",
    title:"Whole-Head Burst",
    concept:"Some discharges involve the whole head at once.",
    body:"Generalized spike-wave starts broadly rather than from one small region.",
    keyPoints:["Generalized = widespread","Both sides start together","A long run can fill the page"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Watch the broad run across both sides.",
      verdict:"Whole-head burst",
      subtitle:"Both sides are involved together.",
      why:"The activity appears broadly rather than starting from one focal center.",
      mistake:"Forcing a focal source onto a truly broad pattern.",
    }
  },
  {
    id:49, stage:6, stageTitle:"Clinical Yield",
    title:"First EEG Yield",
    concept:"A routine EEG can be normal in epilepsy.",
    body:"Within 24 hours of a first seizure, a routine EEG finds epileptiform activity only about half the time.",
    keyPoints:["A normal EEG does not rule out epilepsy","Timing matters","Yield is about probability"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A normal routine EEG after a seizure means epilepsy is:",
      options:["Impossible","Still possible"],
      answer:1,
      verdict:"Still possible",
      subtitle:"Routine EEG can miss it.",
      why:"A single routine EEG may find epileptiform activity only about half the time.",
      mistake:"Using one normal EEG to rule out epilepsy.",
    }
  },
  {
    id:50, stage:6, stageTitle:"Clinical Yield",
    title:"Longer Recording",
    concept:"Longer EEG raises the chance of seeing events.",
    body:"A 24-hour recording can detect epileptiform discharges in roughly 80-90% of patients with epilepsy.",
    keyPoints:["Longer time improves yield","Still not perfect","Normal prolonged EEG can still happen"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A 24-hour EEG is more likely to catch discharges because it records:",
      options:["More channels only","More time"],
      answer:1,
      verdict:"More time",
      subtitle:"More time raises yield.",
      why:"Epileptiform activity can be intermittent, so longer recordings catch more chances.",
      mistake:"Assuming more time makes EEG perfect.",
    }
  },
  {
    id:51, stage:6, stageTitle:"Clinical Yield",
    title:"Repeat Studies",
    concept:"Several short EEGs can add information.",
    body:"Multiple 30-60 minute EEGs can approach the yield of a longer recording.",
    keyPoints:["Events are intermittent","Repeats add chances","Practicality matters"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Repeating routine EEGs can help because abnormalities are often:",
      options:["Always present","Intermittent"],
      answer:1,
      verdict:"Intermittent",
      subtitle:"They may appear only sometimes.",
      why:"More recording opportunities can reveal activity missed before.",
      mistake:"Treating EEG yield as all-or-nothing.",
    }
  },
  {
    id:52, stage:6, stageTitle:"Scalp Limits",
    title:"Area Matters",
    concept:"Scalp EEG needs enough cortex involved.",
    body:"A very small cortical area may not create a detectable scalp signal.",
    keyPoints:["Small source can be missed","Larger synchronized area is easier to see","Scalp sensors are distant"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A very small abnormal brain area is:",
      options:["Always visible on scalp EEG","Sometimes missed"],
      answer:1,
      verdict:"Sometimes missed",
      subtitle:"The scalp signal may be too small.",
      why:"Enough synchronized cortex must be involved to reach scalp electrodes consistently.",
      mistake:"Assuming scalp EEG sees every abnormal neuron group.",
    }
  },
  {
    id:53, stage:6, stageTitle:"Scalp Limits",
    title:"Ten to Twenty cm²",
    concept:"Scalp EEG usually needs a sizable source.",
    body:"Roughly 10-20 square centimeters of cortex may be needed for consistent scalp detection.",
    keyPoints:["Surface area matters","Small areas can hide","This is a limitation of scalp EEG"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Consistent scalp detection usually needs a:",
      options:["Tiny point source","Sizable cortical area"],
      answer:1,
      verdict:"Sizable cortical area",
      subtitle:"Area helps the signal reach the scalp.",
      why:"A larger synchronized area creates a stronger scalp field.",
      mistake:"Expecting scalp EEG to detect every tiny source.",
    }
  },
  {
    id:54, stage:6, stageTitle:"Scalp Limits",
    title:"Depth Matters",
    concept:"Deep sources can be harder to see.",
    body:"Mesial temporal, insular, or singulate sources may be too deep for scalp electrodes.",
    keyPoints:["Surface sources are easier","Deep sources can be missed","Distance weakens scalp signal"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Deep brain activity is often:",
      options:["Easier to see","Harder to see"],
      answer:1,
      verdict:"Harder to see",
      subtitle:"Distance weakens the scalp field.",
      why:"Scalp electrodes sit far from deep structures.",
      mistake:"Assuming a normal scalp EEG excludes deep seizure sources.",
    }
  },
  {
    id:55, stage:6, stageTitle:"Scalp Limits",
    title:"Scalp EEG Limits",
    concept:"A normal page can still be useful.",
    body:"Normal EEG results must be interpreted with history, timing, area, and source depth.",
    keyPoints:["Normal is not always no disease","Context matters","Limits should be reported"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A normal scalp EEG should be read with:",
      options:["No clinical context","Clinical context"],
      answer:1,
      verdict:"Clinical context",
      subtitle:"The test has limits.",
      why:"Timing, source size, and source depth all affect what scalp EEG can show.",
      mistake:"Overpromising what a normal EEG can rule out.",
    }
  },
  {
    id:56, stage:6, stageTitle:"Full Cap Training",
    title:"Full Cap: Blink",
    concept:"Use the whole page, not one line.",
    body:"A full cap case asks you to combine field, timing, and anatomy.",
    keyPoints:["Front maximum","Both frontal poles","Not brain"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Full cap case: biggest wave at Fp1/Fp2 during blink. Most likely:",
      options:["Occipital seizure","Eye artifact"],
      answer:1,
      verdict:"Eye artifact",
      subtitle:"Front field plus eye movement.",
      why:"The field is maximal at the frontal polar sensors closest to the eyes.",
      mistake:"Calling a frontal artifact a brain event.",
    }
  },
  {
    id:57, stage:6, stageTitle:"Full Cap Training",
    title:"Full Cap: Montage",
    concept:"Know the display before interpreting.",
    body:"A full cap page must be read with its montage and chain order in mind.",
    keyPoints:["Identify the view","Find the chain","Then localize"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Before localizing a full cap pattern, first check:",
      options:["Only the largest line","The montage and chain"],
      answer:1,
      verdict:"Montage and chain",
      subtitle:"The display determines what each line means.",
      why:"A full cap page is organized by linked channel chains.",
      mistake:"Localizing from one line without knowing the display.",
    }
  },
  {
    id:58, stage:6, stageTitle:"Full Cap Training",
    title:"Full Cap: Focal Field",
    concept:"Find the maximal field across the cap.",
    body:"Full cap localization uses the strongest region and its surrounding spread.",
    keyPoints:["Find maximum","Check neighboring spread","Name side and region"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Full cap case: tap the focal maximum.",
      target:["T3"],
      verdict:"Left temporal maximum",
      subtitle:"T3 is the center of the field.",
      why:"The strongest activity sits in the left temporal region with surrounding spread.",
      mistake:"Choosing a region that only shows later spread.",
    }
  },
  {
    id:59, stage:6, stageTitle:"Full Cap Training",
    title:"Full Cap: Generalized",
    concept:"Recognize when the whole head starts together.",
    body:"A generalized run starts broadly and synchronously rather than from one side.",
    keyPoints:["Both sides together","Broad field","Long run"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Count the waves inside the 1-second bracket. This run is:",
      options:["Focal onset","Generalized pattern"],
      answer:1,
      verdict:"Generalized pattern",
      subtitle:"Both sides begin together.",
      why:"The run involves the whole head at onset rather than spreading from one point.",
      mistake:"Forcing a focal source on a broad synchronous pattern.",
    }
  },
  {
    id:60, stage:6, stageTitle:"Full Cap Training",
    title:"Full Cap: Final Report",
    concept:"The final answer combines trace and patient.",
    body:"A good full cap interpretation answers the clinical question.",
    keyPoints:["Use the trace","Use the patient story","State the practical meaning"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Measure the run, then use the story. Best final meaning:",
      options:["Normal awake rhythm","Emergency seizure state"],
      answer:1,
      verdict:"Emergency seizure state",
      subtitle:"Trace plus patient story changes urgency.",
      why:"Continuous seizure waves in an unresponsive or confused adult are urgent.",
      mistake:"Naming only the waveform and ignoring the clinical question.",
    }
  },
];

(function reorderForBeginnerPath() {
  var groups = [
    {
      stage: 1,
      title: 'Map Science',
      ids: [31, 32, 33, 34, 35, 36, 1]
    },
    {
      stage: 2,
      title: 'Page Science',
      ids: [37, 38, 39, 41, 42, 2, 40, 3, 43, 44, 45]
    },
    {
      stage: 3,
      title: 'Normal and Limits',
      ids: [4, 5, 6, 7, 8, 49, 50, 51, 52, 53, 54, 55]
    },
    {
      stage: 4,
      title: 'Artifacts and Look-alikes',
      ids: [14, 15, 16, 17, 18, 9, 10, 11, 12, 13, 29]
    },
    {
      stage: 5,
      title: 'Abnormal Patterns',
      ids: [19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 46, 47, 48, 30]
    },
    {
      stage: 6,
      title: 'Full Cap Training',
      ids: [56, 57, 58, 59, 60]
    }
  ];
  var byId = {};
  EEG_EXERCISES.forEach(function (exercise) {
    byId[exercise.id] = exercise;
  });

  EEG_EXERCISES = [];
  groups.forEach(function (group) {
    group.ids.forEach(function (id) {
      var exercise = byId[id];
      if (!exercise) return;
      exercise.stage = group.stage;
      exercise.stageTitle = group.title;
      EEG_EXERCISES.push(exercise);
    });
  });
}());
