var EEG_EXERCISES = [

  // ── STAGE 1: FOUNDATIONS ─────────────────────────────────────────────────
  {
    id:1, stage:1, stageTitle:"Foundations",
    title:"The 10–20 Electrode System",
    concept:"Electrode placement is the grammar of EEG.",
    body:"The 10–20 system places electrodes at defined percentages of head measurements. Labels identify standardized scalp regions: F frontal, C central, P parietal, O occipital, T temporal, and Fp frontopolar. Even numbers = right, odd = left, and z = midline. This course uses a reduced teaching display; modern T7/T8 correspond to the legacy labels T3/T4 used internally by the simulator.",
    keyPoints:["Odd = left, even = right, z = midline","Letters identify standardized scalp regions, not a proven cortical source","T7/T8 are the modern names for legacy T3/T4"],
    imageNote:"Standard 10–20 electrode positions.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Electrode O2 is on which side?",
      options:["Left hemisphere","Right hemisphere"],
      answer:1,
      verdict:"Right hemisphere",
      subtitle:"Even numbers are always right-sided.",
      why:"O stands for occipital. The number 2 means right hemisphere. In the 10–20 system, even = right, odd = left, z = midline — every time, no exceptions.",
      mistake:"Confusing the number convention. Memorise it once: even = right.",
    }
  },
  {
    id:2, stage:1, stageTitle:"Foundations",
    title:"Montages: Referential vs. Bipolar",
    concept:"How you wire the channels shapes what you see.",
    body:"A referential derivation compares each electrode with a selected reference, which is not electrically silent. A bipolar derivation compares adjacent electrodes in a chain. A phase reversal can mark a local scalp voltage maximum or minimum at the shared electrode, but it does not by itself identify the cortical generator.",
    keyPoints:["Phase reversal can mark a local scalp maximum or minimum","A reference can contain brain or artifact signal","Confirm a field with other montages and technical checks"],
    imageNote:"Same focal spike looks different in referential vs. bipolar.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"In a bipolar chain, a phase reversal at T8 (legacy T4) most directly marks:",
      options:["A proven cortical generator","A local scalp voltage maximum or minimum"],
      answer:1,
      verdict:"Local scalp maximum or minimum",
      subtitle:"The two channels flanking the maximum deflect in opposite directions.",
      why:"Opposite deflections in adjacent bipolar derivations place a local scalp voltage maximum or minimum at their shared electrode. Montage, polarity, the full field, and electrode quality must be checked before drawing a source conclusion.",
      mistake:"Calling a phase reversal the cortical source. A faulty shared electrode can affect every derivation that contains it and can imitate a reversal.",
    }
  },
  {
    id:3, stage:1, stageTitle:"Foundations",
    title:"EEG Frequency Bands",
    concept:"Frequency is the first axis of interpretation.",
    body:"Delta 0.1–<4 Hz · Theta 4–<8 Hz · Alpha 8–13 Hz · Beta >13–30 Hz.\nAlpha is commonly the dominant posterior rhythm of a relaxed awake adult with eyes closed. Persistent unexplained delta in a fully awake adult is generally abnormal after excluding drowsiness, activation, and artifact. Excess beta is nonspecific and may reflect medication or muscle artifact.",
    keyPoints:["Persistent awake delta needs context and artifact checks","Posterior alpha attenuates with eye opening","Excess beta is nonspecific"],
    imageNote:"Live: normal awake EEG — alpha maximal at O1/O2.",
    imageCredit:"PhysioNet EEG Motor Movement/Imagery Dataset (open access)",
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel showing the strongest alpha rhythm.",
      target:["O1","O2"],
      verdict:"Occipital alpha",
      subtitle:"O1 and O2 — the posterior dominant rhythm.",
      why:"Alpha is maximal at the occipital poles. The regular ~10 Hz sinusoidal activity at O1/O2 contrasts with the lower-amplitude, irregular activity at frontal leads.",
      mistake:"Looking at frontal channels. Alpha is a posterior rhythm — frontal channels show beta.",
    }
  },
  {
    id:4, stage:1, stageTitle:"Foundations",
    title:"Normal Awake Adult EEG",
    concept:"Know normal before you can recognise abnormal.",
    body:"Normal adult EEG: posterior dominant rhythm (PDR) 8–13 Hz, well-organised symmetric background, alpha attenuates with eye opening, no epileptiform activity. PDR asymmetry >1 Hz is suspicious for ipsilateral pathology.",
    keyPoints:["PDR 8–13 Hz, posterior, attenuates with eyes open","<1 Hz PDR asymmetry is normal","Anterior low-amplitude beta is normal in alert adults"],
    imageNote:"Live: normal adult awake EEG.",
    imageCredit:"PhysioNet EEG Motor Movement/Imagery Dataset (open access)",
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel carrying the posterior dominant rhythm.",
      target:["O1","O2"],
      verdict:"Posterior dominant rhythm",
      subtitle:"The most important single feature of the normal EEG.",
      why:"The PDR is maximal at the occipital electrodes. In a normal awake adult it sits between 8–13 Hz and is everything else is relatively quiet by comparison.",
      mistake:"Reporting a PDR of 7 Hz as normal in an adult. The lower limit is 8 Hz — anything slower deserves attention.",
    }
  },
  {
    id:5, stage:1, stageTitle:"Foundations",
    title:"Drowsiness & Stage 1 Sleep",
    concept:"The transition from wakefulness changes everything.",
    body:"In drowsiness: PDR slows and becomes intermittent, anterior theta appears, vertex sharp waves emerge at Cz. RMTD — rhythmic temporal theta of drowsiness — is a benign pattern often misread as seizure.",
    keyPoints:["PDR slows in drowsiness — don't over-interpret","V-waves at Cz are normal Stage 1 features","RMTD is benign — sharp theta bursts at temporal in drowsiness"],
    imageNote:"Live: drowsy EEG with vertex sharps and anterior theta.",
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Watch C3 and C4. Vertex sharp waves appear every few seconds — large centrally-maximal negative deflections.",
      verdict:"Vertex sharp waves",
      subtitle:"Physiological events of Stage 1 sleep.",
      why:"Vertex sharp waves are normal Stage 1 sleep transients. They have no afterdischarge, are symmetric at the vertex, and look nothing like a focal spike in context. Don't call them epileptiform.",
      mistake:"Calling vertex sharps epileptiform. The key: they are symmetric, maximal at Cz, and lack an aftergoing slow wave.",
    }
  },
  {
    id:6, stage:1, stageTitle:"Foundations",
    title:"Stage 2 Sleep: Spindles & K-complexes",
    concept:"Sleep spindles and K-complexes define Stage 2.",
    body:"Spindles: 11–16 Hz waxing-waning bursts, 0.5–2 s, maximal Cz. K-complexes: high-amplitude biphasic waves at Cz, often followed by a spindle. Both are normal. Asymmetric spindles → suspect thalamic pathology.",
    keyPoints:["Spindles: 11–16 Hz, waxing-waning, maximal Cz","K-complexes: biphasic, vertex, often stimulus-evoked","Asymmetric spindles → thalamic lesion"],
    imageNote:"Live: Stage 2 sleep with spindles and K-complexes.",
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Watch C3 and C4 for spindles — waxing-waning fast bursts — and K-complexes — sudden large biphasic waves.",
      verdict:"Spindles + K-complexes",
      subtitle:"Thalamocortical signatures of Stage 2 NREM.",
      why:"Spindles are generated by thalamocortical circuits and confirm Stage 2. If you see them only on one side, suspect a thalamic lesion ipsilateral to their absence.",
      mistake:"Calling the fast spindle activity 'fast ictal activity.' Spindles are waxing-waning — ictal fast activity builds and doesn't show this symmetric envelope.",
    }
  },
  {
    id:7, stage:1, stageTitle:"Foundations",
    title:"Sensitivity, Filters & Calibration",
    concept:"Your settings are part of your interpretation.",
    body:"A common display sensitivity is 7 µV/mm. Routine review often begins near a 0.5 Hz high-pass (LFF) and 70 Hz low-pass (HFF), with settings adjusted for the question. Filters attenuate frequencies gradually rather than cutting them off completely, and aggressive settings can distort real waveforms. A notch filter attenuates 50/60 Hz line noise but should not replace correction of the source.",
    keyPoints:["A common sensitivity is 7 µV/mm","Filters attenuate with roll-off and can distort morphology","Review slow activity with an appropriately low high-pass setting"],
    imageNote:"Same segment at different sensitivity settings.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"The LFF is set to 5 Hz. What activity is most attenuated?",
      options:["Beta and gamma (fast activity)","Delta and theta (slow activity below 5 Hz)"],
      answer:1,
      verdict:"Delta and lower theta attenuated",
      subtitle:"A 5 Hz high-pass markedly attenuates slow activity.",
      why:"Raising the high-pass setting to 5 Hz markedly attenuates delta and lower theta and can distort waveform shape; filters have roll-off rather than a brick-wall cutoff.",
      mistake:"Forgetting to check filter settings before interpreting slow activity. Always verify before calling delta 'encephalopathy.'",
    }
  },
  {
    id:8, stage:1, stageTitle:"Foundations",
    title:"Pediatric EEG: Age Matters",
    concept:"The normal EEG is a moving target in childhood.",
    body:"PDR matures from ~3 Hz at 3 months to ~10 Hz by age 15. Delta is normal in young children. Hypnagogic hypersynchrony — high-amplitude 3–5 Hz rhythmic activity in drowsiness — is normal under age 5. Always interpret pediatric EEGs against age-normative data.",
    keyPoints:["PDR matures from 3 Hz (3 months) to 10 Hz (15 years)","Hypnagogic hypersynchrony is normal <5 years","Delta in young children can be normal — consider age"],
    imageNote:"Live: normal 5-year-old EEG — higher amplitude, more theta, slower PDR.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A 3-year-old has a PDR of 7 Hz. Is this abnormal?",
      options:["Yes — 7 Hz is too slow, suggests epilepsy","No — 7 Hz is normal for age 3"],
      answer:1,
      verdict:"Normal for age",
      subtitle:"PDR matures gradually through childhood.",
      why:"At age 3, a PDR of 7–8 Hz is entirely within normal limits. The same finding in a 20-year-old would indicate abnormal background slowing. Paediatric EEG always requires age-matched interpretation.",
      mistake:"Applying adult norms to children. This is one of the most consequential errors in clinical EEG.",
    }
  },

  // ── STAGE 2: NORMAL VARIANTS ─────────────────────────────────────────────
  {
    id:9, stage:2, stageTitle:"Normal Variants",
    title:"Wicket Waves",
    concept:"The most commonly over-read benign pattern.",
    body:"Wicket waves are arciform 6–11 Hz temporal transients seen mainly in drowsiness or light sleep. They may occur singly or in brief trains and usually lack a prominent slow after-wave. Their morphology, state dependence, temporal field, and preserved background together favor a benign variant; no single feature is decisive.",
    keyPoints:["Arciform temporal transients in drowsiness or light sleep","May occur singly or in trains","Use morphology, field, state, and background together"],
    imageNote:"Live: wicket waves in modern T7/T8 (legacy T3/T4) temporal leads during drowsiness.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel where wicket waves are maximal.",
      target:["T3","T4"],
      verdict:"Benign variant",
      subtitle:"Arciform temporal rhythm in drowsiness.",
      why:"The arciform morphology, temporal distribution, drowsy state, preserved background, and lack of a prominent slow after-wave together favor wicket waves.",
      mistake:"Using the absence of a slow after-wave as a stand-alone rule. Apply the full morphology, field, state, and background context.",
    }
  },
  {
    id:10, stage:2, stageTitle:"Normal Variants",
    title:"14 and 6 Hz Positive Spikes",
    concept:"Dramatic-looking. No clinical significance.",
    body:"The 14- and 6-Hz positive spike pattern consists of comb-like, surface-positive posterior temporal bursts during drowsiness or light sleep. Polarity is one clue, not a universal separator from IEDs; morphology, distribution, state, and background must agree. Prevalence varies with age, population, and recording method.",
    keyPoints:["Surface-positive comb-like posterior temporal bursts","Usually seen in drowsiness or light sleep","Polarity must be interpreted with morphology, field, and state"],
    imageNote:"14 and 6 Hz positive bursts during drowsiness.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"14 and 6 Hz positive spikes are surface-positive. Why does polarity matter?",
      options:["Polarity alone proves the diagnosis","Polarity is one clue that must fit morphology, field, and state"],
      answer:1,
      verdict:"Polarity is one useful clue",
      subtitle:"Interpret direction with morphology, field, and state.",
      why:"For this named benign variant, surface-positive polarity supports the interpretation when the comb morphology, posterior temporal distribution, and sleep-wake state also fit.",
      mistake:"Using polarity alone to declare a transient benign or epileptiform.",
    }
  },
  {
    id:11, stage:2, stageTitle:"Normal Variants",
    title:"RMTD — Rhythmic Midtemporal Theta of Drowsiness",
    concept:"Looks exactly like a seizure. Isn't.",
    body:"RMTD: sharply contoured, notched theta (5–7 Hz) bursts at midtemporal electrodes in drowsiness. Mimics temporal lobe seizure onset. Key difference: RMTD does not evolve — same frequency, same field, abrupt start and stop. No clinical correlate.",
    keyPoints:["Theta bursts in temporal region during drowsiness","Does NOT evolve — frequency and field stay fixed","Sharply notched morphology is the trap"],
    imageNote:"Live: drowsy EEG — watch temporal leads for RMTD-like theta bursts.",
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Watch T7/T8 (legacy T3/T4). Notice theta bursts that remain stereotyped without progressive evolution.",
      verdict:"Stereotyped, non-evolving rhythm",
      subtitle:"The drowsy temporal pattern favors RMTD.",
      why:"RMTD remains relatively stereotyped in frequency, morphology, and field and occurs in drowsiness without a clinical correlate. Lack of evolution supports RMTD but is not, by itself, a universal seizure exclusion rule.",
      mistake:"Calling any rhythmic temporal pattern ictal without assessing evolution, state, field, artifact, and clinical correlation.",
    }
  },
  {
    id:12, stage:2, stageTitle:"Normal Variants",
    title:"Small Sharp Spikes (BSSS)",
    concept:"Tiny, fleeting, and harmless.",
    body:"SSS (benign sporadic sleep spikes): <50 µV, <50 ms, monophasic or biphasic, NREM sleep only. Disappear during REM and wakefulness. No aftergoing slow wave. The combination of small size, brevity, and NREM-only occurrence defines them as benign.",
    keyPoints:["<50 µV amplitude, <50 ms duration","NREM sleep only — disappear in wakefulness and REM","No aftergoing slow wave"],
    imageNote:"Small sharp spike during Stage 2 sleep — compare amplitude to background.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A 45 ms, <30 µV monophasic transient in NREM sleep with no afterdischarge is:",
      options:["A temporal epileptiform discharge","A benign small sharp spike"],
      answer:1,
      verdict:"Benign small sharp spike",
      subtitle:"Small, brief, NREM-only, no afterdischarge.",
      why:"All criteria for SSS are met: brief (<50 ms), small (<50 µV), NREM-only, monophasic, no afterdischarge. These are benign and should not be reported as epileptiform.",
      mistake:"Calling them temporal IEDs based on location alone. Amplitude, duration, and sleep stage together define SSS.",
    }
  },
  {
    id:13, stage:2, stageTitle:"Normal Variants",
    title:"SREDA",
    concept:"The rare variant most readers have never seen — until they diagnose a seizure incorrectly.",
    body:"SREDA: sustained rhythmic theta (5–7 Hz) or alpha, bilateral parieto-temporal, in an awake asymptomatic patient. Lasts 20 s to several minutes. No clinical correlate, no post-ictal slowing. Seen during hyperventilation.",
    keyPoints:["Bilateral sustained theta/alpha during wakefulness","Patient asymptomatic — no clinical correlate","No post-ictal slowing — the key seizure indicator"],
    imageNote:"SREDA: sudden-onset bilateral theta, no symptoms, no post-ictal slowing.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Sustained bilateral 6 Hz theta in an awake, asymptomatic patient with no post-event slowing — which interpretation is favored?",
      options:["NCSE based on rhythm alone","SREDA, after confirming the characteristic pattern and context"],
      answer:1,
      verdict:"SREDA — benign",
      subtitle:"Characteristic morphology and unchanged clinical state favor SREDA.",
      why:"SREDA is a rare benign variant whose characteristic distribution, relatively monomorphic course, preserved background, and lack of a clinical correlate favor the diagnosis. No single negative feature excludes NCSE in every case.",
      mistake:"Classifying a sustained rhythm from waveform appearance alone without the recording state, evolution, background, and patient correlation.",
    }
  },

  // ── STAGE 3: ARTIFACTS ────────────────────────────────────────────────────
  {
    id:14, stage:3, stageTitle:"Artifacts",
    title:"Eye Blink & Eye Movement Artifacts",
    concept:"The eyes are generators, not just bystanders.",
    body:"The cornea is positive relative to the retina. Blinking: symmetric bifrontal negative deflection. Lateral eye movements: opposite polarity at Fp1 vs Fp2. Most common artifact in clinical EEG.",
    keyPoints:["Bifrontal distribution (Fp1, Fp2, F3, F4)","Blinks: symmetric bilateral negative deflection","Lateral eye movements: opposite polarity at Fp1 vs Fp2"],
    imageNote:"Live: eye blink artifact — watch the frontal leads.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap where the eye blink artifact is largest.",
      target:["Fp1","Fp2"],
      verdict:"Frontopolar artifact",
      subtitle:"The corneoretinal dipole projects most strongly to Fp1/Fp2.",
      why:"A large, stereotyped bifrontal field that coincides with blinking or eye movement strongly supports ocular artifact. Review EOG channels or video and the posterior attenuation before deciding.",
      mistake:"Calling a bifrontal transient cerebral or ocular from field shape alone without checking eye channels, video, timing, and montage.",
    }
  },
  {
    id:15, stage:3, stageTitle:"Artifacts",
    title:"Muscle (EMG) Artifact",
    concept:"The brain's noisiest impostor.",
    body:"Muscle artifact is usually irregular, high-frequency activity, often prominent over frontotemporal or lateral electrodes near cranial muscles. Jaw clenching or tension may increase it, while relaxation may reduce it. Video, examination maneuvers, field, and response to relaxation support—but do not alone prove—the interpretation.",
    keyPoints:["Irregular high-frequency activity is typical","Frontotemporal or lateral predominance is common","Correlate with jaw activity, video, field, and relaxation"],
    imageNote:"Live: muscle burst at temporal electrodes — watch T7/T8 (legacy T3/T4).",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel most contaminated by muscle artifact.",
      target:["T3","T4"],
      verdict:"Temporalis EMG",
      subtitle:"T7 and T8 (legacy T3/T4) lie near the temporalis muscle.",
      why:"The high-frequency irregular burst at T7/T8 (legacy T3/T4) is consistent with temporalis EMG. Correlation with jaw activity and improvement with relaxation support the artifact interpretation.",
      mistake:"Calling temporal fast activity ictal or artifactual from frequency alone; check evolution, field, video, and response to a reproducible maneuver.",
    }
  },
  {
    id:16, stage:3, stageTitle:"Artifacts",
    title:"Cardiac (EKG) Artifact",
    concept:"A regular rhythm that isn't cerebral.",
    body:"Cardiac artifact produces deflections with a consistent temporal relationship to the QRS complex. Its scalp distribution varies with the reference, electrode contacts, body habitus, and pulse transmission. Regularity raises suspicion, but QRS time-locking and montage review are the stronger checks.",
    keyPoints:["Confirm a consistent relationship to the ECG QRS","Distribution depends on reference and electrode contacts","Regularity alone does not exclude cerebral periodic activity"],
    imageNote:"Live: cardiac artifact — regular sharp spikes at 75 bpm.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel where cardiac artifact is most prominent.",
      target:["T3","T4"],
      verdict:"Cardiac artifact",
      subtitle:"Time-locking to the ECG supports cardiac artifact.",
      why:"Cardiac artifact is identified by a consistent relationship to the QRS complexes on the ECG channel. Its distribution depends on the reference and electrode contacts; regularity alone is not diagnostic.",
      mistake:"Using regularity alone to separate cardiac artifact from cerebral periodic activity. Confirm QRS time-locking and review another montage.",
    }
  },
  {
    id:17, stage:3, stageTitle:"Artifacts",
    title:"Sweat & Slow Artifacts",
    concept:"Very slow waves that aren't delta.",
    body:"Sweat can produce very slow, high-amplitude baseline drift through changing electrode-skin potentials; its distribution may be diffuse or electrode-dependent. Glossokinetic artifact is often frontally prominent and linked to tongue movement. A higher high-pass setting may attenuate the drift but can also remove or distort cerebral slow activity, so technical and physiologic correlation remains essential.",
    keyPoints:["Very slow drift can arise from changing electrode-skin potentials","Glossokinetic activity correlates with tongue movement","Filter changes can attenuate artifact and cerebral slow activity"],
    imageNote:"Sweat artifact: wide sinusoidal baseline drift across multiple channels.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Very slow undulating drift appears with sweating and unstable electrode baselines. What is favored?",
      options:["Diffuse cerebral slowing from rate alone","Sweat/electrode-skin artifact, after technical confirmation"],
      answer:1,
      verdict:"Sweat artifact",
      subtitle:"Context and electrode behavior favor sweat-related drift.",
      why:"The very slow baseline shifts, sweating, and unstable electrode behavior favor a noncerebral source. Frequency alone cannot prove artifact; inspect electrodes, montage, video, and the underlying background.",
      mistake:"Calling very slow drift cerebral or artifactual from frequency alone without technical correlation.",
    }
  },
  {
    id:18, stage:3, stageTitle:"Artifacts",
    title:"60 Hz Noise & Electrode Pops",
    concept:"The environment intrudes on your recording.",
    body:"Line noise is a regular high-frequency artifact that may be focal with poor electrode contact or widespread with environmental interference. An electrode pop is a transient caused by abrupt contact change. A cerebral discharge usually has a physiologically plausible field, but a limited field can appear in very few channels and one faulty electrode can contaminate every derivation that contains it.",
    keyPoints:["Line noise may be focal or widespread","A faulty electrode affects every derivation that contains it","A limited field raises uncertainty rather than proving artifact"],
    imageNote:"60 Hz artifact on single channel (impedance) vs. diffuse (environmental).",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A sharp transient appears only at F8, with nothing on any adjacent electrode. This is:",
      options:["Definitely a focal F8 discharge","Suspect electrode artifact and verify"],
      answer:1,
      verdict:"Suspect artifact; verify",
      subtitle:"An isolated transient needs technical and field checks.",
      why:"The absence of a clear neighboring field makes electrode artifact more likely, but it is not proof. Check contact and impedance, inspect every derivation containing F8, change montage, and correlate with video, EOG, and ECG.",
      mistake:"Making a definite artifact or epileptiform call from one display channel without technical checks and montage review.",
    }
  },

  // ── STAGE 4: PATHOLOGICAL PATTERNS ───────────────────────────────────────
  {
    id:19, stage:4, stageTitle:"Pathological Patterns",
    title:"Spikes and Sharp Waves: Criteria",
    concept:"Knowing the criteria prevents both over- and under-diagnosis.",
    body:"Spike and sharp wave are descriptive duration terms: a spike lasts 20 to <70 ms and a sharp wave 70–200 ms. IFCN assessment considers six features: pointed multiphasic morphology, duration distinct from background, waveform asymmetry, a possible slow after-wave, background disruption, and a plausible scalp field. No single feature establishes epileptiformity.",
    keyPoints:["Spike: 20 to <70 ms; sharp wave: 70–200 ms","Assess the six IFCN morphology and field features","No slow after-wave or other single feature is mandatory"],
    imageNote:"Live: focal temporal spike — watch T7 (legacy T3).",
    imageCredit:"Temple University EEG Corpus (TUAB) — open access",
    interaction:{
      type:"observe",
      prompt:"Watch T7 (legacy T3). Compare the pointed waveform, asymmetry, background disruption, possible slow after-wave, and scalp field.",
      verdict:"Use the full IFCN feature set",
      subtitle:"A slow after-wave is helpful, not mandatory.",
      why:"Epileptiform interpretation depends on the combination of morphology, duration, asymmetry, possible slow after-wave, background disruption, and a plausible scalp field.",
      mistake:"Using one feature—such as pointedness or a slow tail—as a stand-alone diagnostic rule.",
    }
  },
  {
    id:20, stage:4, stageTitle:"Pathological Patterns",
    title:"Focal Interictal Epileptiform Discharges",
    concept:"Where is it? How often? What context?",
    body:"Focal IEDs support a propensity for focal seizures in the appropriate clinical context and can provide approximate scalp localization. Report distribution, field, state, frequency, and uncertainty. Use the current syndrome term self-limited epilepsy with centrotemporal spikes (SeLECTS) when the full electroclinical criteria are met.",
    keyPoints:["IEDs support—but do not independently diagnose—epilepsy","Scalp localization is approximate","Report distribution, field, state, frequency, and uncertainty"],
    imageNote:"Live: left temporal spike with a T7 (legacy T3) scalp maximum.",
    imageCredit:"Temple University EEG Corpus (TUAB) — open access",
    interaction:{
      type:"channel-tap",
      prompt:"Tap the electrode at the local scalp maximum (the phase-reversal point in this bipolar chain).",
      target:["T3"],
      verdict:"Left temporal IED",
      subtitle:"T7 (legacy T3) is the local scalp maximum.",
      why:"The phase reversal places a local scalp voltage maximum or minimum at T7 (legacy T3) in this synthetic bipolar chain. It helps describe the field but does not prove a unique cortical generator.",
      mistake:"Calling the scalp maximum the cortical source. Confirm the field across montages and state localization as approximate.",
    }
  },
  {
    id:21, stage:4, stageTitle:"Pathological Patterns",
    title:"Generalised Epileptiform Discharges",
    concept:"Both hemispheres, simultaneously.",
    body:"Classic 3 Hz spike-wave: bilateral synchronous, frontal predominance, abrupt onset/offset, associated with absence. Polyspike-wave → juvenile myoclonic epilepsy. Slow spike-wave (<2.5 Hz) → Lennox-Gastaut syndrome.",
    keyPoints:["3 Hz spike-wave: absence epilepsy, frontal predominance","Polyspike-wave: JME pattern","Slow (<2.5 Hz) spike-wave: Lennox-Gastaut"],
    imageNote:"Live: 3 Hz generalised spike-wave in bursts.",
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Count the spike-wave complexes over any 3-second window during a burst.",
      verdict:"3 Hz generalised spike-wave",
      subtitle:"Bilateral, synchronous, frontal-predominant.",
      why:"You should count approximately 9 complexes in 3 seconds, confirming the 3 Hz rate. The bursts start and stop abruptly, are bilateral with frontal predominance, and the background is flat between bursts — classic absence.",
      mistake:"Calling slow (<2.5 Hz) generalised spike-wave 'absence' in a child. Slow spike-wave means Lennox-Gastaut, a much more severe syndrome.",
    }
  },
  {
    id:22, stage:4, stageTitle:"Pathological Patterns",
    title:"Focal Delta Slowing",
    concept:"Slow waves tell you where the problem is.",
    body:"Persistent focal slowing indicates focal cerebral dysfunction but is etiologically nonspecific. It can accompany structural lesions, postictal or peri-ictal states, migraine, inflammation, or other focal disturbances. Rhythmic focal delta may increase concern for seizures in some contexts, but ictal classification requires evolution, rate-duration criteria, or an electroclinical correlate.",
    keyPoints:["Focal slowing indicates focal dysfunction, not a specific lesion","Polymorphic and rhythmic slowing have different implications","Correlate with history, examination, imaging, and the recording course"],
    imageNote:"Live: continuous left temporal polymorphic delta.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel with the most prominent slow activity.",
      target:["T3","F3","C3"],
      verdict:"Left temporal focal delta",
      subtitle:"Focal cerebral dysfunction; cause remains open.",
      why:"The slow activity is maximal over the left temporal-central region, including T7 (legacy T3), F3, and C3. This localizes the scalp abnormality but does not determine whether the cause is structural, postictal, inflammatory, or another focal process.",
      mistake:"Equating focal slowing with one diagnosis. Report its distribution and persistence, then correlate with the clinical history and appropriate investigations.",
    }
  },
  {
    id:23, stage:4, stageTitle:"Pathological Patterns",
    title:"Periodic Discharges",
    concept:"Repetition with a rhythm — a dangerous sign.",
    body:"Lateralized periodic discharges (LPDs) are unilateral periodic patterns associated with focal cerebral dysfunction and increased seizure risk. They meet ACNS ictal-interictal continuum (IIC) criteria when periodic discharges average >1 to ≤2.5 Hz, or when a 0.5–1 Hz pattern has a plus modifier or fluctuation. IIC is an EEG descriptor, not a diagnosis or automatic treatment indication.",
    keyPoints:["LPDs are associated with increased seizure risk","Frequency and modifiers determine whether ACNS IIC criteria are met","IIC requires electroclinical interpretation"],
    imageNote:"Live: LPDs — regular 1 Hz sharp-slow over right hemisphere.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the hemisphere where the periodic discharges are maximal.",
      target:["Fp2","F4","C4","T4","O2"],
      verdict:"Right hemisphere LPDs",
      subtitle:"Right-sided LPDs carry increased seizure risk.",
      why:"The periodic activity is maximal over the right hemisphere. A 1 Hz pattern alone does not automatically meet IIC criteria; plus modifiers, fluctuation, clinical context, and the recording course matter.",
      mistake:"Calling every LPD ictal—or benign—from frequency alone. Describe the pattern and apply the full ACNS criteria.",
    }
  },

  // ── STAGE 5: SEIZURE RECOGNITION ─────────────────────────────────────────
  {
    id:24, stage:5, stageTitle:"Seizure Recognition",
    title:"What Makes a Seizure on EEG",
    concept:"Evolution strongly supports a seizure, but criteria and context decide.",
    body:"Evolution in frequency, morphology, or location strongly supports ictal activity, but it is not the only route to an electrographic seizure. In ACNS critical-care terminology, an electrographic seizure is epileptiform discharges averaging >2.5 Hz for at least 10 seconds, or a definitely evolving pattern lasting at least 10 seconds. A time-locked clinical correlate can establish an electroclinical seizure. Postictal slowing is supportive, not confirmatory.",
    keyPoints:["Evolution may involve frequency, morphology, or location","ACNS electrographic seizure criteria use rate and duration thresholds","Clinical correlation and postictal context matter"],
    imageNote:"Live: temporal lobe seizure — theta onset evolving to alpha then slowing.",
    imageCredit:"CHB-MIT Scalp EEG Database (PhysioNet, open access)",
    interaction:{
      type:"observe",
      prompt:"Watch T7 (legacy T3) for the earliest visible scalp change and follow how frequency, morphology, and distribution change over time.",
      verdict:"Definitely evolving pattern",
      subtitle:"Sequential change strongly supports ictal activity.",
      why:"The synthetic pattern begins with low-amplitude temporal theta, changes morphology and frequency, spreads, and then slows. Duration, evolution, and clinical correlation determine seizure classification.",
      mistake:"Using evolution as an all-or-none shortcut. Some seizures meet rate-and-duration criteria without clear evolution, while some evolving-looking artifacts are not cerebral.",
    }
  },
  {
    id:25, stage:5, stageTitle:"Seizure Recognition",
    title:"Temporal Lobe Seizure",
    concept:"The most common focal seizure in adults.",
    body:"A temporal seizure may show rhythmic temporal theta or alpha activity with evolving morphology, frequency, or distribution. The earliest visible scalp maximum gives approximate lateralizing information; postictal unilateral slowing can support that interpretation but does not prove the cortical seizure-onset zone.",
    keyPoints:["Track the earliest visible scalp change","Evolution and spread provide supporting evidence","Scalp and postictal localization remain approximate"],
    imageNote:"Live: synthetic left temporal seizure pattern evolving from T7 (legacy T3).",
    imageCredit:"CHB-MIT Scalp EEG Database (PhysioNet, open access)",
    interaction:{
      type:"channel-tap",
      prompt:"Tap the electrode with the earliest visible scalp change.",
      target:["T3"],
      verdict:"Earliest left temporal scalp change",
      subtitle:"T7 (legacy T3) — left mid-temporal scalp electrode.",
      why:"In this synthetic example, the first visible change is maximal at T7 (legacy T3) before appearing more broadly. This supports approximate left temporal lateralization but does not prove the cortical onset zone.",
      mistake:"Equating the largest late wave—or the earliest scalp electrode—with a uniquely proven cortical generator.",
    }
  },
  {
    id:26, stage:5, stageTitle:"Seizure Recognition",
    title:"Generalised Tonic-Clonic Seizure",
    concept:"The full storm — from background to cessation.",
    body:"During a bilateral tonic-clonic seizure, scalp EEG is often substantially obscured by muscle artifact. Generalized fast activity and jerk-locked spike or polyspike-wave may be visible, followed variably by postictal slowing or attenuation. No single postictal feature independently confirms epilepsy or excludes a functional seizure.",
    keyPoints:["Muscle artifact often obscures the tonic and clonic phases","Visible cerebral activity may evolve with the clinical phases","Postictal slowing or attenuation is variable and not diagnostic alone"],
    imageNote:"Live: GTC — tonic fast → clonic spike-wave → post-ictal suppression.",
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Watch the synthetic phase sequence and note where muscle artifact limits scalp interpretation.",
      verdict:"Generalised tonic-clonic seizure",
      subtitle:"Interpret the full electroclinical sequence.",
      why:"A compatible evolving EEG pattern followed by postictal slowing or attenuation may support a convulsive epileptic seizure, but video, artifact review, and the full clinical course are required.",
      mistake:"Using a flat-looking postictal segment as proof of epilepsy or as a stand-alone way to exclude a functional seizure.",
    }
  },
  {
    id:27, stage:5, stageTitle:"Seizure Recognition",
    title:"Non-Convulsive Status Epilepticus",
    concept:"The seizure you miss without EEG.",
    body:"Nonconvulsive status epilepticus is sustained seizure activity without prominent convulsions. Continuous spike-wave, a definitely evolving rhythmic pattern, or some periodic patterns may raise concern, but periodic discharges are not automatically NCSE. Apply ACNS/Salzburg criteria with the examination, video, medications, and recording course.",
    keyPoints:["Persistent altered responsiveness warrants urgent EEG assessment","Apply formal electrographic and electroclinical criteria","Periodic or IIC patterns are not automatically status"],
    imageNote:"Live: generalized periodic activity — recognize when urgent expert correlation is needed.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Continuous spike-wave in an unresponsive patient after a convulsion — best next step?",
      options:["Routine observation only","Urgent expert assessment and continuous EEG for possible NCSE"],
      answer:1,
      verdict:"Urgent expert assessment",
      subtitle:"Possible NCSE requires prompt electroclinical evaluation.",
      why:"Persistent epileptiform activity with impaired responsiveness warrants urgent specialist review and continuous EEG. Diagnosis and treatment follow formal criteria, patient factors, and local emergency protocols.",
      mistake:"Waiting for another convulsion—or prescribing from one pattern alone—without urgent electroclinical assessment.",
    }
  },

  // ── STAGE 6: CLINICAL INTEGRATION ────────────────────────────────────────
  {
    id:28, stage:6, stageTitle:"Clinical Integration",
    title:"Diffuse Encephalopathy Patterns",
    concept:"The whole brain speaks when it is diffusely disturbed.",
    body:"Diffuse cerebral dysfunction often produces generalized slowing and loss of normal organization, but EEG severity and etiology require clinical correlation. Generalized periodic discharges may have triphasic morphology and occur with toxic-metabolic, infectious, structural, medication-related, and other encephalopathies. Triphasic morphology is descriptive and does not by itself distinguish encephalopathy from NCSE.",
    keyPoints:["Generalized slowing is nonspecific and must be interpreted in context","Use the ACNS description GPDs with triphasic morphology when appropriate","Morphology and anterior-posterior lag do not independently exclude NCSE"],
    imageNote:"Live: frontally predominant GPDs with triphasic morphology on a slow background.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the region where these GPDs with triphasic morphology are most prominent.",
      target:["Fp1","Fp2","F3","F4"],
      verdict:"Frontally predominant GPDs",
      subtitle:"Triphasic morphology is a descriptor, not an etiology.",
      why:"This synthetic pattern is frontally predominant and shows an anterior-posterior lag. Those features support the description of GPDs with triphasic morphology, but clinical state, evolution, modifiers, and formal seizure criteria determine whether NCSE remains a concern.",
      mistake:"Using triphasic morphology, frontal predominance, or metabolic illness as a stand-alone exclusion of NCSE.",
    }
  },
  {
    id:29, stage:6, stageTitle:"Clinical Integration",
    title:"Common Interpretive Errors",
    concept:"Knowing where to be wrong is half of being right.",
    body:"Most common misinterpretations: wicket waves called epileptiform, RMTD called seizure, muscle artifact called fast ictal activity, eye blinks called frontal IEDs, SSS called temporal spikes, drowsiness changes called encephalopathy. The antidote: strict criteria + clinical context.",
    keyPoints:["Always apply strict morphological criteria","Context (age, state, clinical history) shapes interpretation","When uncertain: describe the finding, note uncertainty — do not over-diagnose"],
    imageNote:"Live: wicket waves — the most commonly over-read pattern.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Runs of monophasic 8 Hz temporal sharps during drowsiness, no afterdischarge — epileptiform?",
      options:["Yes — report as right temporal IEDs","No — wicket waves, a benign normal variant"],
      answer:1,
      verdict:"Benign variant — not epileptiform",
      subtitle:"Monophasic + temporal + runs + no afterdischarge = wicket waves.",
      why:"The arciform temporal morphology, drowsy state, preserved background, and lack of a prominent slow after-wave together favor wicket waves rather than an IED.",
      mistake:"Using a single shortcut. Wicket identification depends on the combined morphology, field, state, and background.",
    }
  },
  {
    id:30, stage:6, stageTitle:"Clinical Integration",
    title:"Clinical Correlation: The Final Principle",
    concept:"EEG is a test. A test needs a context.",
    body:"The same pattern means different things in different patients. Always integrate: age, clinical history, reason for referral, medications, recording state. A good report synthesises findings with the clinical question — it doesn't just list patterns.",
    keyPoints:["Same pattern, different contexts = different diagnoses","Medications (benzodiazepines, AEDs) alter EEG","The report conclusion should answer the clinical question"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A confused 60-year-old has persistent 3 Hz generalized spike-wave. What is the safer impression?",
      options:["Childhood absence syndrome from waveform alone","Possible NCSE requiring urgent electroclinical evaluation"],
      answer:1,
      verdict:"Possible NCSE — correlate urgently",
      subtitle:"Age and impaired responsiveness change the differential.",
      why:"Persistent generalized spike-wave with acute confusion raises concern for NCSE, but age and waveform alone do not establish it. Apply electrographic and electroclinical criteria with examination, video, medication history, and the recording course.",
      mistake:"Diagnosing either childhood absence epilepsy or NCSE from waveform and age alone.",
    }
  },
  {
    id:31, stage:6, stageTitle:"Full Cap Foundations",
    title:"Nasion and Inion",
    concept:"The 10-20 map starts from reliable landmarks.",
    body:"The front-back head measurement starts at the nasion and ends at the inion.",
    keyPoints:["Nasion = bridge of nose","Inion = bony back point","Measurements make placement reproducible"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"The front-to-back measurement starts at:",
      options:["Temple to temple","Nose bridge to back bump"],
      answer:1,
      verdict:"Nose bridge to back bump",
      subtitle:"Nasion to inion.",
      why:"Those landmarks are easy to find on different patients.",
      mistake:"Starting the map from a vague hairline or face shape.",
    }
  },
  {
    id:32, stage:6, stageTitle:"Full Cap Foundations",
    title:"Preauricular Points",
    concept:"The side-to-side measurement uses points near the ears.",
    body:"The second main measurement runs from one preauricular point to the other.",
    keyPoints:["Preauricular = just in front of each ear","This anchors left-right placement","The map needs front-back and side-side lines"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"The side-to-side measurement uses points near the:",
      options:["Eyes","Ears"],
      answer:1,
      verdict:"Ears",
      subtitle:"Preauricular points sit just before each ear.",
      why:"These points anchor the left-right line across the head.",
      mistake:"Using the eyes as the side-to-side anchor.",
    }
  },
  {
    id:33, stage:6, stageTitle:"Full Cap Foundations",
    title:"10 and 20",
    concept:"The numbers come from measurement increments.",
    body:"The 10-20 system divides head distances into 10% and 20% steps.",
    keyPoints:["Measure the head","Mark percentages","Place sensors at intersections"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"In 10-20, the 10 and 20 are:",
      options:["Channel counts","Measurement percentages"],
      answer:1,
      verdict:"Measurement percentages",
      subtitle:"The map is built from measured distances.",
      why:"Marks are placed at 10% and 20% intervals.",
      mistake:"Treating 10-20 as just a list of sensor names.",
    }
  },
  {
    id:34, stage:6, stageTitle:"Full Cap Foundations",
    title:"Intersections",
    concept:"Sensors go where measured lines cross.",
    body:"Front-back, side-side, circumferential, and transverse marks create sensor positions.",
    keyPoints:["Lines are measured","Crossings become sensor spots","This makes the cap reproducible"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Watch how measured lines create sensor positions.",
      verdict:"Measured crossings",
      subtitle:"The cap is a map, not a guess.",
      why:"Electrodes are placed where measured head-map lines intersect.",
      mistake:"Thinking sensors are placed by eye.",
    }
  },
  {
    id:35, stage:6, stageTitle:"Full Cap Foundations",
    title:"Near the Middle",
    concept:"Electrode distance comes from the measured map, not number size.",
    body:"C4 is closer to the midline than T8 because those are their standardized scalp positions. Odd and even numbers reliably indicate side, but numeric magnitude is not a general medial-to-lateral distance code.",
    keyPoints:["Odd and even indicate left and right","Use the electrode map for distance from midline","T8 is a lateral temporal position"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Which is closer to the middle?",
      options:["T8","C4"],
      answer:1,
      verdict:"C4",
      subtitle:"C4 is nearer the midline on the standard map.",
      why:"T8 is a lateral temporal electrode; this relationship comes from the standardized positions, not because 8 is larger than 4.",
      mistake:"Inferring electrode distance from numeric magnitude instead of checking the map.",
    }
  },
  {
    id:36, stage:6, stageTitle:"Full Cap Foundations",
    title:"The Z Line",
    concept:"Z marks the center line.",
    body:"Midline electrodes use z because they sit on neither left nor right.",
    keyPoints:["z = zero/midline","Fz, Cz, Pz sit in the middle","Midline is a reference line"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Cz sits on the:",
      options:["Right side","Middle line"],
      answer:1,
      verdict:"Middle line",
      subtitle:"z means the midline.",
      why:"Midline sensors are neither odd-left nor even-right.",
      mistake:"Reading z as a side number.",
    }
  },
  {
    id:37, stage:6, stageTitle:"Display Basics",
    title:"Channel",
    concept:"A channel is one displayed comparison.",
    body:"In EEG, a visible line often shows the difference between two inputs.",
    keyPoints:["Two inputs go in","One line comes out","That line is a channel or derivation"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A channel is best thought of as:",
      options:["The whole cap","One displayed comparison"],
      answer:1,
      verdict:"One displayed comparison",
      subtitle:"Two inputs become one line.",
      why:"The displayed line is the output of a comparison.",
      mistake:"Thinking one channel always means one raw electrode.",
    }
  },
  {
    id:38, stage:6, stageTitle:"Display Basics",
    title:"Chain",
    concept:"A chain links several neighboring comparisons.",
    body:"A temporal chain moves from front to side to back along one path.",
    keyPoints:["Channels can be linked","A linked string is a chain","Chains organize the page"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A chain is:",
      options:["One isolated sensor","A linked row of channels"],
      answer:1,
      verdict:"Linked row of channels",
      subtitle:"The page is organized in chains.",
      why:"A chain lets you follow activity across neighboring sensor pairs.",
      mistake:"Reading each line without noticing its neighbors.",
    }
  },
  {
    id:39, stage:6, stageTitle:"Display Basics",
    title:"Page Layout",
    concept:"The bipolar page has an order.",
    body:"A common display stacks left temporal, left parasagittal, midline, right parasagittal, and right temporal chains.",
    keyPoints:["The page follows the head","Left chains appear together","Right chains appear together"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Watch the page as chains are stacked from left to right.",
      verdict:"Organized page",
      subtitle:"The display mirrors the head map.",
      why:"The chain order helps you locate patterns across the cap.",
      mistake:"Treating the page order as random.",
    }
  },
  {
    id:40, stage:6, stageTitle:"Display Basics",
    title:"ECG Line",
    concept:"A heart channel often appears at the bottom.",
    body:"A separate ECG channel helps compare EEG marks with heartbeat timing.",
    keyPoints:["ECG records heart timing","It helps identify heart artifact","It is not a brain channel"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"The bottom ECG channel helps check:",
      options:["Hair thickness","Heartbeat timing"],
      answer:1,
      verdict:"Heartbeat timing",
      subtitle:"It helps separate brain from heart artifact.",
      why:"Regular EEG marks can be compared with the ECG rhythm.",
      mistake:"Ignoring the ECG line when sharp marks repeat regularly.",
    }
  },
  {
    id:41, stage:6, stageTitle:"Display Basics",
    title:"Average Reference",
    concept:"Average reference subtracts the instantaneous mean of selected electrodes.",
    body:"In an average-reference montage, each electrode is compared with the instantaneous arithmetic mean of the included, usable EEG electrodes. The reference is not a physical 'whole-head' voltage and can be distorted by bad channels, incomplete coverage, or large focal activity. Bipolar and average-reference montages are complementary views of the same recorded potentials.",
    keyPoints:["Bipolar derivations compare electrode pairs","Average reference uses the mean of included usable electrodes","Channel selection and artifacts can bias the computed reference"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Average reference compares an electrode with:",
      options:["Only the next electrode","The mean of the included usable EEG electrodes"],
      answer:1,
      verdict:"Mean of included usable electrodes",
      subtitle:"It is a computed reference, not a silent point.",
      why:"The instantaneous mean of the selected usable electrodes is subtracted from each channel. Bad or excluded channels and uneven scalp coverage can change that mean.",
      mistake:"Calling the computed mean a neutral whole-head truth or including grossly artifactual channels without review.",
    }
  },
  {
    id:42, stage:6, stageTitle:"Display Basics",
    title:"Montage Choice",
    concept:"No view is neutral.",
    body:"Changing the montage can change what is easy or hard to see.",
    keyPoints:["A montage is a display view","Views have strengths","Interpretation starts by knowing the view"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Before interpreting, first check:",
      options:["The patient initials only","The display view"],
      answer:1,
      verdict:"The display view",
      subtitle:"The montage shapes the picture.",
      why:"The same signal can look different in different montages.",
      mistake:"Interpreting a page without knowing how it is displayed.",
    }
  },
  {
    id:43, stage:6, stageTitle:"Eye Artifact",
    title:"Eye Dipole",
    concept:"The eye has a front-positive and back-negative side.",
    body:"The cornea is positive and the retina is negative.",
    keyPoints:["Cornea = front of eye","Retina = back of eye","This creates a dipole"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"The front of the eye is the:",
      options:["Retina","Cornea"],
      answer:1,
      verdict:"Cornea",
      subtitle:"The cornea is relatively positive.",
      why:"Eye movement creates a signal because the eye has polarity.",
      mistake:"Treating eye movement as just mechanical motion.",
    }
  },
  {
    id:44, stage:6, stageTitle:"Eye Artifact",
    title:"Bell Phenomenon",
    concept:"During a blink, the eyes roll upward.",
    body:"That upward movement creates a large frontal signal.",
    keyPoints:["Blink moves the eye upward","Front sensors see it strongly","Both frontal poles can deflect"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A blink is largest near:",
      options:["Back sensors","Front sensors"],
      answer:1,
      verdict:"Front sensors",
      subtitle:"The eyes sit in front.",
      why:"The upward eye movement projects strongly to Fp1 and Fp2.",
      mistake:"Calling a blink a frontal brain wave.",
    }
  },
  {
    id:45, stage:6, stageTitle:"Normal Rhythm",
    title:"Eyes Closed Alpha",
    concept:"Alpha is common during relaxed wakefulness.",
    body:"Alpha is often around 10 per second and strongest posteriorly when eyes are closed.",
    keyPoints:["Awake and relaxed","Eyes closed strengthens alpha","Posterior sensors often show it best"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Alpha is commonly strongest when eyes are:",
      options:["Open and scanning","Closed and relaxed"],
      answer:1,
      verdict:"Closed and relaxed",
      subtitle:"A relaxed eyes-closed state brings it out.",
      why:"Alpha is a normal wakeful rhythm that is often posterior and around 10 Hz.",
      mistake:"Calling normal alpha an abnormal rhythm.",
    }
  },
  {
    id:46, stage:6, stageTitle:"Abnormal Fields",
    title:"Left Temporal Field",
    concept:"A focal discharge has a maximal area.",
    body:"A left temporal abnormality is strongest in the left temporal chain.",
    keyPoints:["Focal means one main area","Temporal means side head","Maximal means strongest"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the left temporal maximum.",
      target:["T3"],
      verdict:"Left temporal maximum",
      subtitle:"T7 (legacy T3) is the left mid-temporal electrode.",
      why:"The synthetic abnormality has its local scalp maximum in the left temporal chain. This describes the recorded field without proving a unique cortical source.",
      mistake:"Equating the scalp maximum with a uniquely localized cortical generator.",
    }
  },
  {
    id:47, stage:6, stageTitle:"Abnormal Fields",
    title:"Right Posterior Field",
    concept:"A field can be strongest at the back-right head.",
    body:"Posterior right activity may be maximal near O2.",
    keyPoints:["Posterior means back","Right uses even numbers","O2 is back-right"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the right posterior maximum.",
      target:["O2"],
      verdict:"Right posterior maximum",
      subtitle:"O2 is the back-right sensor.",
      why:"The maximal field is posterior and right-sided.",
      mistake:"Calling all posterior activity occipital without checking side.",
    }
  },
  {
    id:48, stage:6, stageTitle:"Abnormal Fields",
    title:"Whole-Head Burst",
    concept:"Some discharges involve the whole head at once.",
    body:"Generalized spike-wave starts broadly rather than from one small region.",
    keyPoints:["Generalized = widespread","Both sides start together","A long run can fill the page"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Watch the broad run across both sides.",
      verdict:"Whole-head burst",
      subtitle:"Both sides are involved together.",
      why:"The activity appears broadly rather than starting from one focal center.",
      mistake:"Forcing a focal source onto a truly broad pattern.",
    }
  },
  {
    id:49, stage:6, stageTitle:"Clinical Yield",
    title:"First EEG Yield",
    concept:"A routine EEG can be normal in epilepsy.",
    body:"A single routine EEG has limited sensitivity for interictal epileptiform discharges, and published yield varies substantially with population, timing, sleep capture, activation procedures, and recording duration. A normal result therefore does not rule out epilepsy.",
    keyPoints:["A normal routine EEG does not rule out epilepsy","Yield varies by protocol and patient population","Timing, sleep, activation, and duration matter"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A normal routine EEG after a seizure means epilepsy is:",
      options:["Impossible","Still possible"],
      answer:1,
      verdict:"Still possible",
      subtitle:"Routine EEG can miss it.",
      why:"Interictal discharges can be intermittent, and routine-EEG sensitivity varies across settings. The result must be integrated with the clinical history.",
      mistake:"Using one normal EEG to rule out epilepsy.",
    }
  },
  {
    id:50, stage:6, stageTitle:"Clinical Yield",
    title:"Longer Recording",
    concept:"Longer EEG raises the chance of seeing events.",
    body:"Longer recordings often increase the chance of capturing interictal discharges or events because abnormalities may be intermittent and sleep may be sampled. The gain is not a universal percentage: it depends on epilepsy type, referral population, timing, recording method, and whether the target is an IED or a typical clinical event.",
    keyPoints:["Longer sampling often improves yield","The size of the gain varies by population and protocol","A normal prolonged EEG still does not exclude epilepsy"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A 24-hour EEG is more likely to catch discharges because it records:",
      options:["More channels only","More time"],
      answer:1,
      verdict:"More time",
      subtitle:"More time raises yield.",
      why:"Epileptiform activity can be intermittent, so longer recordings catch more chances.",
      mistake:"Assuming more time makes EEG perfect.",
    }
  },
  {
    id:51, stage:6, stageTitle:"Clinical Yield",
    title:"Repeat Studies",
    concept:"Several short EEGs can add information.",
    body:"Multiple 30-60 minute EEGs can approach the yield of a longer recording.",
    keyPoints:["Events are intermittent","Repeats add chances","Practicality matters"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Repeating routine EEGs can help because abnormalities are often:",
      options:["Always present","Intermittent"],
      answer:1,
      verdict:"Intermittent",
      subtitle:"They may appear only sometimes.",
      why:"More recording opportunities can reveal activity missed before.",
      mistake:"Treating EEG yield as all-or-nothing.",
    }
  },
  {
    id:52, stage:6, stageTitle:"Scalp Limits",
    title:"Area Matters",
    concept:"Scalp EEG needs enough cortex involved.",
    body:"A very small cortical area may not create a detectable scalp signal.",
    keyPoints:["Small source can be missed","Larger synchronized area is easier to see","Scalp sensors are distant"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A very small abnormal brain area is:",
      options:["Always visible on scalp EEG","Sometimes missed"],
      answer:1,
      verdict:"Sometimes missed",
      subtitle:"The scalp signal may be too small.",
      why:"Enough synchronized cortex must be involved to reach scalp electrodes consistently.",
      mistake:"Assuming scalp EEG sees every abnormal neuron group.",
    }
  },
  {
    id:53, stage:6, stageTitle:"Scalp Limits",
    title:"Source Visibility Has No Fixed Cutoff",
    concept:"Area matters, but geometry and signal quality matter too.",
    body:"There is no universal cortical-area threshold for scalp detection. Experimental estimates vary, and visibility also depends on synchrony, source orientation and depth, amplitude, skull and scalp conductivity, electrode coverage, montage, background activity, and noise.",
    keyPoints:["Larger synchronized areas are generally easier to detect","No single cm² cutoff applies to every source","Orientation, depth, montage, and noise also shape visibility"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"All else equal, which source is generally easier to detect at the scalp?",
      options:["Tiny point source","Sizable cortical area"],
      answer:1,
      verdict:"Sizable cortical area",
      subtitle:"Area helps, but it is not a fixed threshold.",
      why:"A larger synchronized area often produces a stronger field, while orientation, depth, montage, conductivity, and noise can still change detectability.",
      mistake:"Expecting scalp EEG to detect every tiny source.",
    }
  },
  {
    id:54, stage:6, stageTitle:"Scalp Limits",
    title:"Depth Matters",
    concept:"Deep sources can be harder to see.",
    body:"Mesial temporal, insular, or cingulate activity can be difficult to detect or localize with scalp EEG. Depth contributes, but orientation, synchrony, intervening tissues, electrode coverage, and propagation also influence the visible scalp field.",
    keyPoints:["Deep sources can be difficult to detect or localize","Depth is only one determinant of visibility","Orientation, synchrony, coverage, and propagation matter"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Deep brain activity is often:",
      options:["Easier to see","Harder to see"],
      answer:1,
      verdict:"Harder to see",
      subtitle:"Distance weakens the scalp field.",
      why:"Distance and intervening tissues can attenuate deep activity, while orientation and propagation determine whether a recognizable scalp field appears.",
      mistake:"Assuming a normal scalp EEG excludes deep seizure sources.",
    }
  },
  {
    id:55, stage:6, stageTitle:"Scalp Limits",
    title:"Scalp EEG Limits",
    concept:"A normal page can still be useful.",
    body:"Normal EEG results must be interpreted with history, timing, area, and source depth.",
    keyPoints:["Normal is not always no disease","Context matters","Limits should be reported"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A normal scalp EEG should be read with:",
      options:["No clinical context","Clinical context"],
      answer:1,
      verdict:"Clinical context",
      subtitle:"The test has limits.",
      why:"Timing, source size, and source depth all affect what scalp EEG can show.",
      mistake:"Overpromising what a normal EEG can rule out.",
    }
  },
  {
    id:56, stage:6, stageTitle:"Full Cap Training",
    title:"Full Cap: Blink",
    concept:"Use the whole page, not one line.",
    body:"A full cap case asks you to combine field, timing, and anatomy.",
    keyPoints:["Front maximum","Both frontal poles","Not brain"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Full cap case: biggest wave at Fp1/Fp2 during blink. Most likely:",
      options:["Occipital seizure","Eye artifact"],
      answer:1,
      verdict:"Eye artifact",
      subtitle:"Front field plus eye movement.",
      why:"The field is maximal at the frontal polar sensors closest to the eyes.",
      mistake:"Calling a frontal artifact a brain event.",
    }
  },
  {
    id:57, stage:6, stageTitle:"Full Cap Training",
    title:"Full Cap: Montage",
    concept:"Know the display before interpreting.",
    body:"A full cap page must be read with its montage and chain order in mind.",
    keyPoints:["Identify the view","Find the chain","Then localize"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Before localizing a full cap pattern, first check:",
      options:["Only the largest line","The montage and chain"],
      answer:1,
      verdict:"Montage and chain",
      subtitle:"The display determines what each line means.",
      why:"A full cap page is organized by linked channel chains.",
      mistake:"Localizing from one line without knowing the display.",
    }
  },
  {
    id:58, stage:6, stageTitle:"Full Cap Training",
    title:"Full Cap: Focal Field",
    concept:"Find the maximal field across the cap.",
    body:"Full cap localization uses the strongest region and its surrounding spread.",
    keyPoints:["Find maximum","Check neighboring spread","Name side and region"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Full cap case: tap the focal maximum.",
      target:["T3"],
      verdict:"Left temporal maximum",
      subtitle:"T7 (legacy T3) is the local scalp maximum.",
      why:"The strongest recorded activity sits in the left temporal region with surrounding spread. This localizes the scalp field approximately, not a unique cortical generator.",
      mistake:"Calling the scalp maximum the proven cortical source or choosing only a later area of spread.",
    }
  },
  {
    id:59, stage:6, stageTitle:"Full Cap Training",
    title:"Full Cap: Generalized",
    concept:"Recognize when the whole head starts together.",
    body:"A generalized run starts broadly and synchronously rather than from one side.",
    keyPoints:["Both sides together","Broad field","Long run"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Count the waves inside the 1-second bracket. This run is:",
      options:["Focal onset","Generalized pattern"],
      answer:1,
      verdict:"Generalized pattern",
      subtitle:"Both sides begin together.",
      why:"The run involves the whole head at onset rather than spreading from one point.",
      mistake:"Forcing a focal source on a broad synchronous pattern.",
    }
  },
  {
    id:60, stage:6, stageTitle:"Full Cap Training",
    title:"Full Cap: Final Report",
    concept:"The final answer combines trace and patient.",
    body:"A good full cap interpretation answers the clinical question.",
    keyPoints:["Use the trace","Use the patient story","State the practical meaning"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Measure the run, then use the story. Best final meaning:",
      options:["Normal awake rhythm","Possible NCSE requiring urgent expert assessment"],
      answer:1,
      verdict:"Possible NCSE — urgent assessment",
      subtitle:"The trace and patient state require electroclinical correlation.",
      why:"A persistent generalized epileptiform pattern with impaired responsiveness raises concern for NCSE. Formal criteria, examination, video, medications, and the recording course determine the final diagnosis.",
      mistake:"Naming the waveform as definite status—or dismissing it—without electroclinical criteria and context.",
    }
  },
  {
    id:61, stage:1, stageTitle:"From Cortex to Scalp",
    title:"Synaptic Currents",
    concept:"Scalp EEG reflects summed postsynaptic currents more than individual action potentials.",
    body:"Postsynaptic currents last long enough for many aligned cortical neurons to add together into a measurable field.",
    keyPoints:["Population signal","Postsynaptic currents","Temporal summation"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"What contributes most to routine scalp EEG?",
      options:["Single axonal spikes","Summed postsynaptic currents"],
      answer:1,
      verdict:"Summed postsynaptic currents",
      subtitle:"EEG is a population field, not a single-neuron recording.",
      why:"Slower postsynaptic currents can overlap across many neurons; brief action potentials usually cancel at scalp distance.",
      mistake:"Treating an EEG trace as a direct view of individual neurons firing.",
    }
  },
  {
    id:62, stage:1, stageTitle:"From Cortex to Scalp",
    title:"Population Synchrony",
    concept:"Alignment and timing determine whether tiny fields reinforce or cancel.",
    body:"Parallel pyramidal cells firing with coordinated timing produce a stronger summed field than scattered, asynchronous cells.",
    keyPoints:["Aligned cells","Coordinated timing","Constructive summation"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Which cortical population is easier to detect at the scalp?",
      options:["Aligned and synchronous","Scattered and asynchronous"],
      answer:0,
      verdict:"Aligned and synchronous",
      subtitle:"Geometry and timing let weak fields add.",
      why:"When similarly oriented pyramidal cells are active together, their extracellular fields reinforce instead of cancelling.",
      mistake:"Assuming that more active neurons always produce a stronger scalp signal regardless of orientation or timing.",
    }
  },
  {
    id:63, stage:1, stageTitle:"From Cortex to Scalp",
    title:"Dipole Orientation",
    concept:"Source orientation changes how a cortical field projects to scalp electrodes.",
    body:"Folded cortex creates differently oriented generators, so equally active patches can produce very different scalp maps.",
    keyPoints:["Cortical folding","Source orientation","Scalp projection"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Can two equally active cortical patches create different scalp patterns?",
      options:["No, activity alone decides","Yes, orientation matters"],
      answer:1,
      verdict:"Orientation matters",
      subtitle:"The cortical sheet is folded, so its fields point in different directions.",
      why:"A source's position and orientation determine how its voltage field reaches each electrode.",
      mistake:"Assuming the largest scalp channel sits directly over a unique generator.",
    }
  },
  {
    id:64, stage:1, stageTitle:"From Cortex to Scalp",
    title:"Volume Conduction",
    concept:"Electrical fields spread passively through brain, fluid, skull, and scalp.",
    body:"One cortical generator can influence many electrodes at essentially the same moment, with different amplitudes and polarities.",
    keyPoints:["Passive spread","Shared source","Broad scalp field"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A waveform appears in several nearby channels at once. Is one shared source possible?",
      options:["No, each channel needs its own source","Yes, fields spread through tissue"],
      answer:1,
      verdict:"One source can reach many channels",
      subtitle:"Channels sample a shared volume-conducted field.",
      why:"Scalp electrodes measure voltage differences within a field that has spread through conductive tissue.",
      mistake:"Counting every affected channel as a separate brain generator.",
    }
  },
  {
    id:65, stage:1, stageTitle:"From Cortex to Scalp",
    title:"The Skull as a Filter",
    concept:"The skull reduces amplitude and blurs fine spatial detail.",
    body:"By the time a field reaches the scalp, it is weaker and broader than it was at the cortical surface.",
    keyPoints:["Attenuation","Spatial blur","Limited localization"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Compared with a cortical-surface recording, scalp EEG is usually:",
      options:["Sharper and larger","Broader and smaller"],
      answer:1,
      verdict:"Broader and smaller",
      subtitle:"Tissue between cortex and electrode acts as a spatial filter.",
      why:"Skull resistance attenuates the field, while conductive layers spread it across the scalp.",
      mistake:"Reading a broad scalp maximum as the exact boundary of the active cortex.",
    }
  },
  {
    id:66, stage:1, stageTitle:"From Cortex to Scalp",
    title:"The Inverse Problem",
    concept:"A scalp voltage map does not identify one unique brain source.",
    body:"Different combinations of sources can produce similar scalp measurements, so localization needs models and clinical context.",
    keyPoints:["Non-unique solution","Model assumptions","Clinical context"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Does one scalp map prove one unique cortical source?",
      options:["Yes","No"],
      answer:1,
      verdict:"No unique source",
      subtitle:"Scalp measurements constrain possibilities; they do not solve location by themselves.",
      why:"This is the EEG inverse problem: multiple source configurations can explain the same electrode voltages.",
      mistake:"Presenting visual localization as certainty without a model, montage comparison, or other evidence.",
    }
  },
];

(function reorderForBeginnerPath() {
  var groups = [
    { stage: 1, title: 'From Cortex to Scalp', ids: [61, 62, 63, 64, 65, 66, 52, 53, 54, 55] },
    { stage: 2, title: 'The Electrode Map', ids: [31, 32, 33, 34, 35, 36, 1] },
    { stage: 3, title: 'Channels and Montages', ids: [37, 38, 39, 40, 41, 42, 2, 7] },
    { stage: 4, title: 'Rhythms, Wake, and Sleep', ids: [3, 4, 5, 6, 8, 45] },
    { stage: 5, title: 'Artifacts', ids: [43, 44, 14, 15, 16, 17, 18] },
    { stage: 6, title: 'Benign Look-alikes', ids: [9, 10, 11, 12, 13, 29] },
    { stage: 7, title: 'Abnormal Backgrounds', ids: [19, 20, 21, 22, 23] },
    { stage: 8, title: 'Seizures and Status', ids: [24, 25, 26, 27, 28, 30, 46, 47, 48] },
    { stage: 9, title: 'Yield and Clinical Context', ids: [49, 50, 51] },
    { stage: 10, title: 'Full Cap Synthesis', ids: [56, 57, 58, 59, 60] }
  ];
  var byId = {};
  EEG_EXERCISES.forEach(function (exercise) {
    byId[exercise.id] = exercise;
  });
  var expectedCount = Object.keys(byId).length;
  var seen = {};

  EEG_EXERCISES = [];
  groups.forEach(function (group) {
    group.ids.forEach(function (id) {
      var exercise = byId[id];
      if (!exercise) throw new Error('Unknown EEG lesson id in module map: ' + id);
      if (seen[id]) throw new Error('Duplicate EEG lesson id in module map: ' + id);
      seen[id] = true;
      exercise.stage = group.stage;
      exercise.stageTitle = group.title;
      EEG_EXERCISES.push(exercise);
    });
  });

  if (EEG_EXERCISES.length !== expectedCount) {
    throw new Error('EEG module map does not include every lesson.');
  }

  window.EEG_MODULES = groups.map(function (group) {
    return { id: group.stage, title: group.title, lessonIds: group.ids.slice() };
  });
}());
