var EEG_EXERCISES = [

  // ── STAGE 1: FOUNDATIONS ─────────────────────────────────────────────────
  {
    id:1, stage:1, stageTitle:"Foundations",
    title:"The 10–20 Electrode System",
    concept:"Electrode placement is the grammar of EEG.",
    body:"The 10–20 system places electrodes at defined percentages of skull length. Labels encode location: F frontal, C central, P parietal, O occipital, T temporal, Fp frontopolar. Even numbers = right hemisphere, odd = left, z = midline.",
    keyPoints:["Odd = left, even = right, z = midline","Letters encode lobe: F, C, P, O, T, Fp","Without knowing the electrode, a finding means nothing"],
    imageNote:"Standard 10–20 electrode positions.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Electrode O2 is on which side?",
      options:["Left hemisphere","Right hemisphere"],
      answer:1,
      verdict:"Right hemisphere",
      subtitle:"Even numbers are always right-sided.",
      why:"O stands for occipital. The number 2 means right hemisphere. In the 10–20 system, even = right, odd = left, z = midline — every time, no exceptions.",
      mistake:"Confusing the number convention. Memorise it once: even = right.",
    }
  },
  {
    id:2, stage:1, stageTitle:"Foundations",
    title:"Montages: Referential vs. Bipolar",
    concept:"How you wire the channels shapes what you see.",
    body:"Referential: each electrode vs. a common reference — shows true waveform shape. Bipolar: adjacent electrodes compared in a chain — localises by phase reversal. The same brain activity looks completely different in each montage.",
    keyPoints:["Phase reversal in bipolar = source location","Referential shows true morphology","Same EEG looks different in each montage"],
    imageNote:"Same focal spike looks different in referential vs. bipolar.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"In a bipolar chain, a phase reversal at T4 means:",
      options:["T4 has a bad electrode","The discharge maximum is at T4"],
      answer:1,
      verdict:"Phase reversal = source",
      subtitle:"The two channels flanking the maximum deflect in opposite directions.",
      why:"In a bipolar montage, when adjacent channel pairs point away from each other, the electrode between them is closest to the generator. This is the phase reversal — and it localises the source.",
      mistake:"Thinking phase reversal means artifact. A bad electrode causes a spike on ONE channel only, with no logical field.",
    }
  },
  {
    id:3, stage:1, stageTitle:"Foundations",
    title:"EEG Frequency Bands",
    concept:"Frequency is the first axis of interpretation.",
    body:"Delta <4 Hz · Theta 4–8 Hz · Alpha 8–13 Hz · Beta >13 Hz.\nAlpha is the dominant rhythm of a relaxed awake adult with eyes closed. Delta in an awake adult is always abnormal. Excess beta suggests benzodiazepines or barbiturates.",
    keyPoints:["Delta in awake adults = always abnormal","Alpha blocks with eye opening","Excess beta = medications (benzodiazepines, barbiturates)"],
    imageNote:"Live: normal awake EEG — alpha maximal at O1/O2.",
    imageCredit:"PhysioNet EEG Motor Movement/Imagery Dataset (open access)",
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel showing the strongest alpha rhythm.",
      target:["O1","O2"],
      verdict:"Occipital alpha",
      subtitle:"O1 and O2 — the posterior dominant rhythm.",
      why:"Alpha is maximal at the occipital poles. The regular ~10 Hz sinusoidal activity at O1/O2 contrasts with the lower-amplitude, irregular activity at frontal leads.",
      mistake:"Looking at frontal channels. Alpha is a posterior rhythm — frontal channels show beta.",
    }
  },
  {
    id:4, stage:1, stageTitle:"Foundations",
    title:"Normal Awake Adult EEG",
    concept:"Know normal before you can recognise abnormal.",
    body:"Normal adult EEG: posterior dominant rhythm (PDR) 8–13 Hz, well-organised symmetric background, alpha attenuates with eye opening, no epileptiform activity. PDR asymmetry >1 Hz is suspicious for ipsilateral pathology.",
    keyPoints:["PDR 8–13 Hz, posterior, attenuates with eyes open","<1 Hz PDR asymmetry is normal","Anterior low-amplitude beta is normal in alert adults"],
    imageNote:"Live: normal adult awake EEG.",
    imageCredit:"PhysioNet EEG Motor Movement/Imagery Dataset (open access)",
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel carrying the posterior dominant rhythm.",
      target:["O1","O2"],
      verdict:"Posterior dominant rhythm",
      subtitle:"The most important single feature of the normal EEG.",
      why:"The PDR is maximal at the occipital electrodes. In a normal awake adult it sits between 8–13 Hz and is everything else is relatively quiet by comparison.",
      mistake:"Reporting a PDR of 7 Hz as normal in an adult. The lower limit is 8 Hz — anything slower deserves attention.",
    }
  },
  {
    id:5, stage:1, stageTitle:"Foundations",
    title:"Drowsiness & Stage 1 Sleep",
    concept:"The transition from wakefulness changes everything.",
    body:"In drowsiness: PDR slows and becomes intermittent, anterior theta appears, vertex sharp waves emerge at Cz. RMTD — rhythmic temporal theta of drowsiness — is a benign pattern often misread as seizure.",
    keyPoints:["PDR slows in drowsiness — don't over-interpret","V-waves at Cz are normal Stage 1 features","RMTD is benign — sharp theta bursts at temporal in drowsiness"],
    imageNote:"Live: drowsy EEG with vertex sharps and anterior theta.",
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Watch C3 and C4. Vertex sharp waves appear every few seconds — large centrally-maximal negative deflections.",
      verdict:"Vertex sharp waves",
      subtitle:"Physiological events of Stage 1 sleep.",
      why:"Vertex sharp waves are normal Stage 1 sleep transients. They have no afterdischarge, are symmetric at the vertex, and look nothing like a focal spike in context. Don't call them epileptiform.",
      mistake:"Calling vertex sharps epileptiform. The key: they are symmetric, maximal at Cz, and lack an aftergoing slow wave.",
    }
  },
  {
    id:6, stage:1, stageTitle:"Foundations",
    title:"Stage 2 Sleep: Spindles & K-complexes",
    concept:"Sleep spindles and K-complexes define Stage 2.",
    body:"Spindles: 11–16 Hz waxing-waning bursts, 0.5–2 s, maximal Cz. K-complexes: high-amplitude biphasic waves at Cz, often followed by a spindle. Both are normal. Asymmetric spindles → suspect thalamic pathology.",
    keyPoints:["Spindles: 11–16 Hz, waxing-waning, maximal Cz","K-complexes: biphasic, vertex, often stimulus-evoked","Asymmetric spindles → thalamic lesion"],
    imageNote:"Live: Stage 2 sleep with spindles and K-complexes.",
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Watch C3 and C4 for spindles — waxing-waning fast bursts — and K-complexes — sudden large biphasic waves.",
      verdict:"Spindles + K-complexes",
      subtitle:"Thalamocortical signatures of Stage 2 NREM.",
      why:"Spindles are generated by thalamocortical circuits and confirm Stage 2. If you see them only on one side, suspect a thalamic lesion ipsilateral to their absence.",
      mistake:"Calling the fast spindle activity 'fast ictal activity.' Spindles are waxing-waning — ictal fast activity builds and doesn't show this symmetric envelope.",
    }
  },
  {
    id:7, stage:1, stageTitle:"Foundations",
    title:"Sensitivity, Filters & Calibration",
    concept:"Your settings are part of your interpretation.",
    body:"Standard gain: 7 µV/mm. Low-frequency filter (LFF) at 1 Hz removes drift. High-frequency filter (HFF) at 70 Hz removes muscle artifact. Notch filter removes 50/60 Hz line noise. Raising the LFF eliminates slow waves — always check settings before interpreting delta activity.",
    keyPoints:["Standard sensitivity: 7 µV/mm","HFF at 70 Hz removes gamma and muscle","LFF at 1 Hz removes drift — but also cuts delta if set too high"],
    imageNote:"Same segment at different sensitivity settings.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"The LFF is set to 5 Hz. What activity has been removed?",
      options:["Beta and gamma (fast activity)","Delta and theta (slow activity below 5 Hz)"],
      answer:1,
      verdict:"Delta and theta removed",
      subtitle:"The LFF cuts everything below its cutoff frequency.",
      why:"Raising the low-frequency filter eliminates frequencies below its cutoff. At 5 Hz, all delta and most theta disappear — including any genuine pathological slowing.",
      mistake:"Forgetting to check filter settings before interpreting slow activity. Always verify before calling delta 'encephalopathy.'",
    }
  },
  {
    id:8, stage:1, stageTitle:"Foundations",
    title:"Pediatric EEG: Age Matters",
    concept:"The normal EEG is a moving target in childhood.",
    body:"PDR matures from ~3 Hz at 3 months to ~10 Hz by age 15. Delta is normal in young children. Hypnagogic hypersynchrony — high-amplitude 3–5 Hz rhythmic activity in drowsiness — is normal under age 5. Always interpret pediatric EEGs against age-normative data.",
    keyPoints:["PDR matures from 3 Hz (3 months) to 10 Hz (15 years)","Hypnagogic hypersynchrony is normal <5 years","Delta in young children can be normal — consider age"],
    imageNote:"Live: normal 5-year-old EEG — higher amplitude, more theta, slower PDR.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A 3-year-old has a PDR of 7 Hz. Is this abnormal?",
      options:["Yes — 7 Hz is too slow, suggests epilepsy","No — 7 Hz is normal for age 3"],
      answer:1,
      verdict:"Normal for age",
      subtitle:"PDR matures gradually through childhood.",
      why:"At age 3, a PDR of 7–8 Hz is entirely within normal limits. The same finding in a 20-year-old would indicate abnormal background slowing. Paediatric EEG always requires age-matched interpretation.",
      mistake:"Applying adult norms to children. This is one of the most consequential errors in clinical EEG.",
    }
  },

  // ── STAGE 2: NORMAL VARIANTS ─────────────────────────────────────────────
  {
    id:9, stage:2, stageTitle:"Normal Variants",
    title:"Wicket Waves",
    concept:"The most commonly over-read benign pattern.",
    body:"Wicket waves: monophasic, arciform, 6–11 Hz, maximal mid-temporal, during drowsiness. Key: they are monophasic — no aftergoing slow wave — and appear in runs, not in isolation. Not epileptiform.",
    keyPoints:["Monophasic = no afterdischarge (the critical distinction)","Appear in runs, temporal distribution","Common source of false epilepsy diagnoses"],
    imageNote:"Live: wicket waves in temporal leads during drowsiness.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel where wicket waves are maximal.",
      target:["T3","T4"],
      verdict:"Benign variant",
      subtitle:"No after-going slow wave.",
      why:"Wicket waves are a normal variant seen during drowsiness. They are monophasic — each arc ends cleanly without a following slow wave. That absence is what makes them benign.",
      mistake:"Mistaking wicket waves for epileptiform discharges. The rule: monophasic + temporal + runs + drowsiness = wicket waves.",
    }
  },
  {
    id:10, stage:2, stageTitle:"Normal Variants",
    title:"14 and 6 Hz Positive Spikes",
    concept:"Dramatic-looking. No clinical significance.",
    body:"Comb-like bursts at 14 Hz and/or 6 Hz, posterior temporal, during drowsiness. Surface-positive polarity — unlike epileptiform discharges which are surface-negative. Found in 20–60% of normal adolescents.",
    keyPoints:["Surface-positive polarity — key distinguishing feature","Maximal posterior temporal, drowsiness/early sleep","Found in up to 60% of normal adolescents"],
    imageNote:"14 and 6 Hz positive bursts during drowsiness.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"14 and 6 Hz positive spikes are surface-positive. Why does polarity matter?",
      options:["It doesn't — polarity is irrelevant","Most epileptiform discharges are surface-negative, so positivity argues against pathology"],
      answer:1,
      verdict:"Polarity is diagnostic",
      subtitle:"Surface-positive = almost always benign.",
      why:"True epileptiform IEDs are surface-negative by convention. Surface-positive sharp transients in the right context — temporal, during drowsiness, comb-like — are almost invariably benign.",
      mistake:"Reporting 14+6 spikes as epileptiform. Their surface-positive polarity, comb morphology, and drowsy state should prevent this.",
    }
  },
  {
    id:11, stage:2, stageTitle:"Normal Variants",
    title:"RMTD — Rhythmic Midtemporal Theta of Drowsiness",
    concept:"Looks exactly like a seizure. Isn't.",
    body:"RMTD: sharply contoured, notched theta (5–7 Hz) bursts at midtemporal electrodes in drowsiness. Mimics temporal lobe seizure onset. Key difference: RMTD does not evolve — same frequency, same field, abrupt start and stop. No clinical correlate.",
    keyPoints:["Theta bursts in temporal region during drowsiness","Does NOT evolve — frequency and field stay fixed","Sharply notched morphology is the trap"],
    imageNote:"Live: drowsy EEG — watch temporal leads for RMTD-like theta bursts.",
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Watch T3/T4. Notice theta bursts that appear and stop without changing frequency or spreading.",
      verdict:"No evolution = not a seizure",
      subtitle:"RMTD starts and stops at a fixed frequency.",
      why:"A temporal lobe seizure starts fast, builds in amplitude, shifts in frequency, and spreads. RMTD just appears and disappears at the same frequency. The absence of evolution is the critical differentiator.",
      mistake:"Treating RMTD as NCSE. Unnecessary IV benzodiazepines have been given because of this mistake.",
    }
  },
  {
    id:12, stage:2, stageTitle:"Normal Variants",
    title:"Small Sharp Spikes (BSSS)",
    concept:"Tiny, fleeting, and harmless.",
    body:"SSS (benign sporadic sleep spikes): <50 µV, <50 ms, monophasic or biphasic, NREM sleep only. Disappear during REM and wakefulness. No aftergoing slow wave. The combination of small size, brevity, and NREM-only occurrence defines them as benign.",
    keyPoints:["<50 µV amplitude, <50 ms duration","NREM sleep only — disappear in wakefulness and REM","No aftergoing slow wave"],
    imageNote:"Small sharp spike during Stage 2 sleep — compare amplitude to background.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A 45 ms, <30 µV monophasic transient in NREM sleep with no afterdischarge is:",
      options:["A temporal epileptiform discharge","A benign small sharp spike"],
      answer:1,
      verdict:"Benign small sharp spike",
      subtitle:"Small, brief, NREM-only, no afterdischarge.",
      why:"All criteria for SSS are met: brief (<50 ms), small (<50 µV), NREM-only, monophasic, no afterdischarge. These are benign and should not be reported as epileptiform.",
      mistake:"Calling them temporal IEDs based on location alone. Amplitude, duration, and sleep stage together define SSS.",
    }
  },
  {
    id:13, stage:2, stageTitle:"Normal Variants",
    title:"SREDA",
    concept:"The rare variant most readers have never seen — until they diagnose a seizure incorrectly.",
    body:"SREDA: sustained rhythmic theta (5–7 Hz) or alpha, bilateral parieto-temporal, in an awake asymptomatic patient. Lasts 20 s to several minutes. No clinical correlate, no post-ictal slowing. Seen during hyperventilation.",
    keyPoints:["Bilateral sustained theta/alpha during wakefulness","Patient asymptomatic — no clinical correlate","No post-ictal slowing — the key seizure indicator"],
    imageNote:"SREDA: sudden-onset bilateral theta, no symptoms, no post-ictal slowing.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Sustained bilateral 6 Hz theta in an awake, asymptomatic patient with no post-ictal slowing — treat for NCSE?",
      options:["Yes — bilateral rhythmic activity requires treatment","No — this is SREDA, a benign normal variant"],
      answer:1,
      verdict:"SREDA — benign",
      subtitle:"Asymptomatic + no post-ictal slowing = not a seizure.",
      why:"SREDA is one of the most important normal variants to know. The patient is asymptomatic during it and there is no post-ictal change — both are incompatible with NCSE.",
      mistake:"Treating SREDA as NCSE exposes the patient to unnecessary IV benzodiazepines and ICU admission.",
    }
  },

  // ── STAGE 3: ARTIFACTS ────────────────────────────────────────────────────
  {
    id:14, stage:3, stageTitle:"Artifacts",
    title:"Eye Blink & Eye Movement Artifacts",
    concept:"The eyes are generators, not just bystanders.",
    body:"The cornea is positive relative to the retina. Blinking: symmetric bifrontal negative deflection. Lateral eye movements: opposite polarity at Fp1 vs Fp2. Most common artifact in clinical EEG.",
    keyPoints:["Bifrontal distribution (Fp1, Fp2, F3, F4)","Blinks: symmetric bilateral negative deflection","Lateral eye movements: opposite polarity at Fp1 vs Fp2"],
    imageNote:"Live: eye blink artifact — watch the frontal leads.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap where the eye blink artifact is largest.",
      target:["Fp1","Fp2"],
      verdict:"Frontopolar artifact",
      subtitle:"The corneoretinal dipole projects most strongly to Fp1/Fp2.",
      why:"Blink artifacts are maximal at the frontal poles, closest to the eyes. The large bifrontal deflections attenuate rapidly posteriorly — confirming they are not cerebral.",
      mistake:"Calling blinks 'frontal slow waves' or 'frontal IEDs.' Ask the patient to close their eyes: blinks stop; cerebral activity continues.",
    }
  },
  {
    id:15, stage:3, stageTitle:"Artifacts",
    title:"Muscle (EMG) Artifact",
    concept:"The brain's noisiest impostor.",
    body:"Muscle artifact: high-frequency (>30 Hz), irregular, low amplitude per wave. Lateral/temporal predominance — the temporalis muscle. Worsens with anxiety, jaw clenching. Ask the patient to relax the jaw to confirm.",
    keyPoints:["High frequency (>30 Hz), irregular, low amplitude","Lateral/temporal predominance (temporalis muscle)","Jaw relaxation resolves it immediately"],
    imageNote:"Live: muscle burst at temporal electrodes — watch T3/T4.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel most contaminated by muscle artifact.",
      target:["T3","T4"],
      verdict:"Temporalis EMG",
      subtitle:"T3 and T4 overlie the temporalis muscle.",
      why:"The high-frequency irregular burst at T3/T4 is EMG from the temporalis muscle, not cerebral activity. A jaw clench creates it; jaw relaxation resolves it immediately.",
      mistake:"Calling temporal muscle burst 'fast ictal activity.' Ictal activity evolves and has a field; muscle artifact stops abruptly with jaw relaxation.",
    }
  },
  {
    id:16, stage:3, stageTitle:"Artifacts",
    title:"Cardiac (EKG) Artifact",
    concept:"A regular rhythm that isn't cerebral.",
    body:"Cardiac artifact: regular, periodic sharp deflections time-locked to QRS. Maximal where the heart's electrical vector intersects the scalp — typically temporal or vertex. Its completely regular interval distinguishes it from epileptiform activity.",
    keyPoints:["Regular rhythm = cardiac — not epileptiform","Check against simultaneously recorded EKG channel","Temporal or vertex — correlates with electrode-vessel proximity"],
    imageNote:"Live: cardiac artifact — regular sharp spikes at 75 bpm.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel where cardiac artifact is most prominent.",
      target:["T3","T4"],
      verdict:"Cardiac artifact",
      subtitle:"Mechanically regular — no cerebral discharge is this precise.",
      why:"Cardiac artifact is most prominent near neck vessels — typically T3 or T4. Its perfectly regular interval matching the heart rate is diagnostic. No epileptiform discharge fires this predictably.",
      mistake:"Calling the regular sharp deflections 'LPDs.' LPDs have variable morphology and slightly irregular periodicity; cardiac artifact is metronomic.",
    }
  },
  {
    id:17, stage:3, stageTitle:"Artifacts",
    title:"Sweat & Slow Artifacts",
    concept:"Very slow waves that aren't delta.",
    body:"Sweat artifact: <0.5 Hz, undulating, high-amplitude, diffuse — from galvanic skin response at electrode sites. Glossokinetic artifact: frontal, rhythmic, linked to tongue movement. Raising the LFF (e.g., to 1–2 Hz) reveals underlying activity.",
    keyPoints:["Sweat: <0.5 Hz, undulating, diffuse, resolves with drying","Glossokinetic: frontal, linked to tongue/speech movements","Raising LFF reveals what's underneath"],
    imageNote:"Sweat artifact: wide sinusoidal baseline drift across multiple channels.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Diffuse very slow (<0.5 Hz) undulating baseline across all channels — is this encephalopathy?",
      options:["Yes — report as diffuse delta slowing","No — this is sweat artifact"],
      answer:1,
      verdict:"Sweat artifact",
      subtitle:"Too slow to be delta — this is galvanic skin response.",
      why:"Sweat artifact is too slow (<0.5 Hz) to be delta (0.5–4 Hz). It affects all channels diffusely and resolves by drying the scalp or cooling the room. Never interpret it as pathological slowing.",
      mistake:"Reporting sweat artifact as 'diffuse delta' — a finding that would prompt urgent clinical workup unnecessarily.",
    }
  },
  {
    id:18, stage:3, stageTitle:"Artifacts",
    title:"60 Hz Noise & Electrode Pops",
    concept:"The environment intrudes on your recording.",
    body:"60 Hz noise: constant, perfectly regular, high-frequency. Single-channel = high-impedance electrode. Widespread = environmental. Electrode pop: single-channel high-amplitude fast transient from momentary contact loss. True cerebral discharges always spread to neighbours.",
    keyPoints:["60 Hz noise: single-channel = electrode; widespread = environment","Electrode pop: single channel, asymmetric rise-fall","True discharges spread to adjacent channels"],
    imageNote:"60 Hz artifact on single channel (impedance) vs. diffuse (environmental).",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"A sharp transient appears only at F8, with nothing on any adjacent electrode. This is:",
      options:["A focal F8 epileptiform discharge","An electrode artifact — true discharges always spread"],
      answer:1,
      verdict:"Electrode artifact",
      subtitle:"True discharges always have a field.",
      why:"Any single-channel transient with no neighbouring projection is an artifact until proven otherwise. True cerebral discharges cannot be confined to one electrode — they always project to adjacent channels.",
      mistake:"Reporting a single-channel transient as a 'right frontotemporal spike.' Checking the field (adjacent channels) must come before any epileptiform call.",
    }
  },

  // ── STAGE 4: PATHOLOGICAL PATTERNS ───────────────────────────────────────
  {
    id:19, stage:4, stageTitle:"Pathological Patterns",
    title:"Spikes and Sharp Waves: Criteria",
    concept:"Knowing the criteria prevents both over- and under-diagnosis.",
    body:"Spike: 20–70 ms, surface-negative, disrupts background, has aftergoing slow wave. Sharp wave: same but 70–200 ms. Both must have a plausible field (spread to neighbours). An isolated sharp transient without these features is not epileptiform.",
    keyPoints:["Spike: 20–70 ms; sharp wave: 70–200 ms","Must have aftergoing slow wave and disrupt background","Must have a plausible field across adjacent electrodes"],
    imageNote:"Live: focal temporal spike — watch T3.",
    imageCredit:"Temple University EEG Corpus (TUAB) — open access",
    interaction:{
      type:"observe",
      prompt:"Watch T3. Each time a spike fires, look for the slow wave that follows it.",
      verdict:"Aftergoing slow wave = epileptiform",
      subtitle:"The slow wave is the defining criterion.",
      why:"The aftergoing slow wave is what separates an epileptiform discharge from any sharp transient. No slow wave = not a spike, no matter how pointed or prominent.",
      mistake:"Calling any sharp transient a 'spike' without checking for the afterdischarge. This single mistake is responsible for most over-diagnoses.",
    }
  },
  {
    id:20, stage:4, stageTitle:"Pathological Patterns",
    title:"Focal Interictal Epileptiform Discharges",
    concept:"Where is it? How often? What context?",
    body:"Focal IEDs indicate focal cortical irritability. Localisation guides surgical planning. Common syndromes: temporal (TLE), frontal (FLE), centrotemporal (Rolandic). Frequency correlates loosely but imperfectly with seizure burden.",
    keyPoints:["Temporal IEDs: most common focal epilepsy pattern","Centrotemporal (Rolandic) spikes: benign childhood epilepsy","Always report lateralisation, localisation, and frequency"],
    imageNote:"Live: left temporal spike with T3 phase reversal.",
    imageCredit:"Temple University EEG Corpus (TUAB) — open access",
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel at the centre of the discharge (phase reversal point).",
      target:["T3"],
      verdict:"Left temporal IED",
      subtitle:"T3 is the epicentre of this discharge.",
      why:"T3 is the source of this left temporal IED. In a bipolar montage, the channels above and below T3 would point away from each other — the classic phase reversal confirming the source location.",
      mistake:"Calling the whole left hemisphere abnormal because multiple channels show the discharge. The focus is T3 — the others show field spread.",
    }
  },
  {
    id:21, stage:4, stageTitle:"Pathological Patterns",
    title:"Generalised Epileptiform Discharges",
    concept:"Both hemispheres, simultaneously.",
    body:"Classic 3 Hz spike-wave: bilateral synchronous, frontal predominance, abrupt onset/offset, associated with absence. Polyspike-wave → juvenile myoclonic epilepsy. Slow spike-wave (<2.5 Hz) → Lennox-Gastaut syndrome.",
    keyPoints:["3 Hz spike-wave: absence epilepsy, frontal predominance","Polyspike-wave: JME pattern","Slow (<2.5 Hz) spike-wave: Lennox-Gastaut"],
    imageNote:"Live: 3 Hz generalised spike-wave in bursts.",
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Count the spike-wave complexes over any 3-second window during a burst.",
      verdict:"3 Hz generalised spike-wave",
      subtitle:"Bilateral, synchronous, frontal-predominant.",
      why:"You should count approximately 9 complexes in 3 seconds, confirming the 3 Hz rate. The bursts start and stop abruptly, are bilateral with frontal predominance, and the background is flat between bursts — classic absence.",
      mistake:"Calling slow (<2.5 Hz) generalised spike-wave 'absence' in a child. Slow spike-wave means Lennox-Gastaut, a much more severe syndrome.",
    }
  },
  {
    id:22, stage:4, stageTitle:"Pathological Patterns",
    title:"Focal Delta Slowing",
    concept:"Slow waves tell you where the problem is.",
    body:"Focal polymorphic delta over one region = structural lesion until proven otherwise. Rhythmic focal delta can be ictal — look for evolution. Correlate with imaging. Focal theta may indicate subcortical white matter dysfunction.",
    keyPoints:["Focal polymorphic delta = structural lesion until proven otherwise","Rhythmic focal delta can be ictal — look for evolution","Get imaging when focal slowing is unexplained"],
    imageNote:"Live: continuous left temporal polymorphic delta.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel with the most prominent slow activity.",
      target:["T3","F3","C3"],
      verdict:"Left temporal focal delta",
      subtitle:"Structural lesion until proven otherwise.",
      why:"The slow activity is maximal over the left hemisphere (T3, F3, C3). Focal polymorphic delta means there is a structural problem in the underlying cortex — imaging is mandatory.",
      mistake:"Attributing focal delta to 'postictal slowing' without evidence of a preceding seizure. Always get imaging for unexplained focal slowing.",
    }
  },
  {
    id:23, stage:4, stageTitle:"Pathological Patterns",
    title:"Periodic Discharges",
    concept:"Repetition with a rhythm — a dangerous sign.",
    body:"Lateralised periodic discharges (LPDs): one hemisphere, regular ~1 Hz, acute focal injury + high seizure risk. Generalised periodic discharges (GPDs): bilateral — anoxic injury, metabolic, prion disease. LPDs = ictal-interictal continuum.",
    keyPoints:["LPDs = acute focal injury + high seizure risk","GPDs = anoxic injury, metabolic, prion disease","Ictal-interictal continuum — correlate clinically"],
    imageNote:"Live: LPDs — regular 1 Hz sharp-slow over right hemisphere.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the hemisphere where the periodic discharges are maximal.",
      target:["Fp2","F4","C4","T4","O2"],
      verdict:"Right hemisphere LPDs",
      subtitle:"Ictal-interictal continuum — urgent evaluation needed.",
      why:"All the periodic activity is on the right (even-numbered channels). The combination of lateralisation and 1 Hz periodicity places this firmly in the ictal-interictal continuum. Continuous EEG monitoring is needed.",
      mistake:"Dismissing LPDs as 'just artifact' because they're too regular. Regularity is the point — it means periodically recurring discharge from a focal injury.",
    }
  },

  // ── STAGE 5: SEIZURE RECOGNITION ─────────────────────────────────────────
  {
    id:24, stage:5, stageTitle:"Seizure Recognition",
    title:"What Makes a Seizure on EEG",
    concept:"Evolution is the hallmark.",
    body:"A seizure: rhythmic activity that evolves in frequency, amplitude, and spatial distribution. Has a clear onset and offset. Post-ictal slowing (delta) confirms and lateralises. Without evolution, a pattern is not a seizure.",
    keyPoints:["Evolution in frequency, amplitude, and field = ictal","Post-ictal slowing confirms seizure onset zone","No evolution = not a seizure (RMTD? SREDA?)"],
    imageNote:"Live: temporal lobe seizure — theta onset evolving to alpha then slowing.",
    imageCredit:"CHB-MIT Scalp EEG Database (PhysioNet, open access)",
    interaction:{
      type:"observe",
      prompt:"Watch for the seizure beginning at T3 (~4 s in). Notice how the activity changes frequency and amplitude over time.",
      verdict:"Ictal — evolution confirmed",
      subtitle:"Frequency, amplitude, and field all change over time.",
      why:"The seizure starts as low-amplitude theta at T3, builds in amplitude, shifts frequency, then slows into post-ictal delta. Evolution across all three dimensions — frequency, amplitude, field — is what makes it ictal.",
      mistake:"Calling RMTD a seizure because it looks like an ictal onset. RMTD starts and stops without any evolution — that is the critical distinction.",
    }
  },
  {
    id:25, stage:5, stageTitle:"Seizure Recognition",
    title:"Temporal Lobe Seizure",
    concept:"The most common focal seizure in adults.",
    body:"TLE: focal onset at anterior temporal electrode, rhythmic theta → alpha build, spread to ipsilateral hemisphere, possible secondary generalisation. Post-ictal unilateral slowing helps lateralise the seizure onset zone.",
    keyPoints:["Onset: focal rhythmic theta at anterior temporal","Builds, slows, spreads — classic evolution","Post-ictal unilateral slowing helps lateralise"],
    imageNote:"Live: left temporal lobe seizure evolving from T3.",
    imageCredit:"CHB-MIT Scalp EEG Database (PhysioNet, open access)",
    interaction:{
      type:"channel-tap",
      prompt:"Tap the channel where the seizure originates.",
      target:["T3"],
      verdict:"Left temporal onset",
      subtitle:"T3 — left anterior temporal.",
      why:"The seizure starts at T3 and spreads to C3, then F3, then contralateral T4. This propagation pattern is the canonical left TLE signature. Post-ictal slowing at T3 confirms the onset zone.",
      mistake:"Tapping T4 because the right side eventually shows activity. Secondary spread does not mean bilateral onset — track where the activity starts, not where it ends up.",
    }
  },
  {
    id:26, stage:5, stageTitle:"Seizure Recognition",
    title:"Generalised Tonic-Clonic Seizure",
    concept:"The full storm — from background to cessation.",
    body:"GTC on EEG: tonic phase → high-amplitude diffuse fast activity. Clonic phase → rhythmic spike-wave slowing from 5 Hz → 2.5 Hz. Post-ictal suppression → diffuse flat trace for seconds to minutes. Post-ictal suppression is highly specific for a true GTC.",
    keyPoints:["Tonic: high-amplitude fast (>10 Hz)","Clonic: spike-wave bursts that progressively slow","Post-ictal suppression: specific for true GTC"],
    imageNote:"Live: GTC — tonic fast → clonic spike-wave → post-ictal suppression.",
    imageCredit:null,
    interaction:{
      type:"observe",
      prompt:"Watch the full cycle: tonic (fast), then clonic (slowing spike-wave), then suppression (flat trace).",
      verdict:"Generalised tonic-clonic seizure",
      subtitle:"Post-ictal suppression is the diagnostic key.",
      why:"A genuinely flat trace for 20–30 seconds after convulsive activity confirms a true GTC. This pattern never occurs in psychogenic non-epileptic events.",
      mistake:"Missing the post-ictal suppression because the recording ends too early. Always continue recording for several minutes after clinical activity stops.",
    }
  },
  {
    id:27, stage:5, stageTitle:"Seizure Recognition",
    title:"Non-Convulsive Status Epilepticus",
    concept:"The seizure you miss without EEG.",
    body:"NCSE: sustained seizure activity without prominent motor signs. Patterns: continuous spike-wave, rhythmic delta/theta with evolution, or periodic discharges. Patient may be confused, unresponsive, or show only subtle twitching. Medical emergency.",
    keyPoints:["Altered consciousness + no convulsions = do EEG urgently","Continuous or near-continuous epileptiform patterns","Response to IV benzodiazepine — clinical + EEG change — is diagnostic"],
    imageNote:"Live: generalised encephalopathy — recognise what needs urgent treatment.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Continuous spike-wave in an unresponsive patient post-convulsion — immediate action?",
      options:["Wait and observe — this may resolve","Treat as NCSE — IV benzodiazepine + urgent neurology"],
      answer:1,
      verdict:"Treat immediately",
      subtitle:"NCSE is a neurological emergency.",
      why:"Every minute of ongoing seizure activity causes neuronal injury. IV benzodiazepine, continuous EEG monitoring, and urgent neurology consultation are the standard response.",
      mistake:"Waiting for more convulsive activity before treating. The whole point of NCSE is that the seizure has already lost its motor component — EEG is the only window.",
    }
  },

  // ── STAGE 6: CLINICAL INTEGRATION ────────────────────────────────────────
  {
    id:28, stage:6, stageTitle:"Clinical Integration",
    title:"Diffuse Encephalopathy Patterns",
    concept:"The whole brain speaks when it is diffusely disturbed.",
    body:"Diffuse encephalopathy: generalised slowing (alpha → theta → delta), loss of normal architecture, triphasic waves in hepatic/uremic encephalopathy, suppression-burst in severe anoxia. Triphasic waves can mimic NCSE — clinical context is essential.",
    keyPoints:["Background slowing = severity of encephalopathy","Triphasic waves: bifrontal, phase-lag, metabolic context","Suppression-burst: severe — anoxia, barbiturates, hypothermia"],
    imageNote:"Live: triphasic waves — bifrontal, 1.8 Hz, on a slow background.",
    imageCredit:null,
    interaction:{
      type:"channel-tap",
      prompt:"Tap the region where triphasic waves are most prominent.",
      target:["Fp1","Fp2","F3","F4"],
      verdict:"Frontal triphasic waves",
      subtitle:"Bifrontal, 1.8 Hz, anterior-to-posterior phase lag.",
      why:"Triphasic waves have frontal predominance with an anterior-to-posterior phase lag — the frontal deflection leads the posterior by milliseconds. This spatial pattern, in a metabolic context, distinguishes them from NCSE.",
      mistake:"Treating triphasic waves as NCSE without clinical context. Metabolic encephalopathy + bifrontal phase-lag = triphasics; treat the metabolic cause.",
    }
  },
  {
    id:29, stage:6, stageTitle:"Clinical Integration",
    title:"Common Interpretive Errors",
    concept:"Knowing where to be wrong is half of being right.",
    body:"Most common misinterpretations: wicket waves called epileptiform, RMTD called seizure, muscle artifact called fast ictal activity, eye blinks called frontal IEDs, SSS called temporal spikes, drowsiness changes called encephalopathy. The antidote: strict criteria + clinical context.",
    keyPoints:["Always apply strict morphological criteria","Context (age, state, clinical history) shapes interpretation","When uncertain: describe the finding, note uncertainty — do not over-diagnose"],
    imageNote:"Live: wicket waves — the most commonly over-read pattern.",
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"Runs of monophasic 8 Hz temporal sharps during drowsiness, no afterdischarge — epileptiform?",
      options:["Yes — report as right temporal IEDs","No — wicket waves, a benign normal variant"],
      answer:1,
      verdict:"Benign variant — not epileptiform",
      subtitle:"Monophasic + temporal + runs + no afterdischarge = wicket waves.",
      why:"This is the most consequential over-read in EEG. Wicket waves cause unnecessary epilepsy diagnoses, driving-licence loss, and antiseizure medication exposure. The criteria are strict — apply them.",
      mistake:"The mistake is the first option. This error has real consequences for patients. Monophasic + runs + temporal + drowsiness = wicket waves, every time.",
    }
  },
  {
    id:30, stage:6, stageTitle:"Clinical Integration",
    title:"Clinical Correlation: The Final Principle",
    concept:"EEG is a test. A test needs a context.",
    body:"The same pattern means different things in different patients. Always integrate: age, clinical history, reason for referral, medications, recording state. A good report synthesises findings with the clinical question — it doesn't just list patterns.",
    keyPoints:["Same pattern, different contexts = different diagnoses","Medications (benzodiazepines, AEDs) alter EEG","The report conclusion should answer the clinical question"],
    imageNote:null,
    imageCredit:null,
    interaction:{
      type:"binary",
      prompt:"3 Hz generalised spike-wave in a 60-year-old with acute confusion — childhood absence epilepsy?",
      options:["Yes — the pattern is classic for absence","No — in a confused adult, this is NCSE until proven otherwise"],
      answer:1,
      verdict:"NCSE in an adult",
      subtitle:"Context transforms interpretation completely.",
      why:"Absence epilepsy is a childhood syndrome. The same 3 Hz pattern in a confused adult is NCSE — a medical emergency requiring immediate treatment. The waveform is identical; the diagnosis is opposite.",
      mistake:"Diagnosing absence epilepsy in an adult based on the waveform alone, without considering age and clinical state.",
    }
  },
];
